{
  "hash": "4e6f4403874f9ea8a99590e0bef162f3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Optimization Basics\"\n---\n\nEverything in AeroSandbox — every airfoil polar, every weight buildup, every trajectory — is designed to sit inside an optimization problem. So before any wings appear, this chapter teaches the machinery that the rest of the book is built on. You will learn the `asb.Opti` lifecycle (declare variables, add constraints, set an objective, solve, extract values) by working a classic nonconvex benchmark; how to scale from 2 design variables to hundreds using vectorized variables; and why AeroSandbox ships its own drop-in replacement for NumPy. If you internalize this one chapter, every later chapter is \"just\" writing physics models inside this same five-call pattern.\n\n## The shape of an engineering design problem {#sec-optimization-basics}\n\nMost engineering design problems, reduced to their mathematical skeleton, look surprisingly alike. They are:\n\n* **Continuous** — the design variables (a wingspan, a cruise altitude) vary smoothly, rather than being discrete choices.\n* **Nonlinear** — the sensitivity of performance to each input changes as you move through the design space.\n* **Nonconvex** — the objective is not always \"curving up\", so local information alone can't certify a global optimum.\n* **Poorly scaled** — variables and their couplings span many orders of magnitude, so the Hessian is ill-conditioned.\n* **Constrained** — the interesting designs live on the boundary of what's allowed: a structure at its stress limit, a wing at its stall margin.\n\nThe classic miniature of the first four properties is the [Rosenbrock function](https://en.wikipedia.org/wiki/Rosenbrock_function) — the \"Hello, World!\" of optimization. Physically, picture a shallow, banana-shaped valley: falling *into* the valley is easy, but the valley floor is nearly flat along its length and curves as it goes, so following it to the true bottom is hard. In code, it's one line:\n\n::: {#eb625248 .cell execution_count=1}\n``` {.python .cell-code}\ndef rosenbrock(x, y):\n    return (1 - x) ** 2 + 100 * (y - x**2) ** 2\n```\n:::\n\n\nHere's what that landscape looks like:\n\n::: {#cell-fig-01-rosenbrock .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![Contours of the Rosenbrock function, log-spaced. The minimum hides at the far end of a nearly-flat, curving valley.](01-optimization-basics_files/figure-html/fig-01-rosenbrock-output-1.png){#fig-01-rosenbrock width=801 height=760 fig-alt='Contour plot of the Rosenbrock function on the domain x in [-2, 2], y in [-1, 3], with log-spaced contour levels shown as gray lines and the global minimum at (1, 1) marked with a star.'}\n:::\n:::\n\n\nWith the picture in mind, the problem statement is simply:\n\n$$ \\underset{x,\\ y}{\\text{minimize}} \\quad (1-x)^2 + 100\\,(y-x^2)^2 $$\n\nThe minimum sits at $(1, 1)$, where the function value is exactly zero — a fact we can verify by hand, which makes this a good first test of the machinery.\n\n## The `Opti` lifecycle {#sec-optimization-basics-lifecycle}\n\nThe core of AeroSandbox is the `Opti` class: an optimization environment where you state a problem in natural mathematical syntax, and a modern gradient-based solver ([IPOPT](https://coin-or.github.io/Ipopt/), with derivatives supplied automatically by [CasADi](https://web.casadi.org/)) finds the optimum. Under the hood, `asb.Opti` extends CasADi's `Opti` class with engineering-design conveniences — variable scaling, log-transforms, frozen variables — that later chapters will use heavily.\n\nEvery `Opti` problem in this book, from 2 variables to thousands, follows the same five-call lifecycle:\n\n1. `opti = asb.Opti()` — create an optimization environment.\n2. `opti.variable(init_guess=...)` — declare each design variable, with an initial guess.\n3. `opti.subject_to(...)` — declare constraints (we'll add one in a moment).\n4. `opti.minimize(...)` — declare the objective.\n5. `sol = opti.solve()`, then `sol(...)` — solve, and evaluate any expression at the optimum.\n\nHere is the whole lifecycle applied to the Rosenbrock problem:\n\n::: {#62e0eb39 .cell execution_count=3}\n``` {.python .cell-code}\nimport aerosandbox as asb  # The standard AeroSandbox import convention\n\nopti = asb.Opti()  # 1. Create an optimization environment\n\nx = opti.variable(init_guess=0)  # 2. Declare variables. Initial guesses are required.\ny = opti.variable(init_guess=0)\n\nopti.minimize(rosenbrock(x, y))  # 4. Declare the objective (no constraints yet)\n\nsol = opti.solve()  # 5. Solve.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThis is Ipopt version 3.14.11, running with linear solver MUMPS 5.4.1.\n\nNumber of nonzeros in equality constraint Jacobian...:        0\nNumber of nonzeros in inequality constraint Jacobian.:        0\nNumber of nonzeros in Lagrangian Hessian.............:        3\n\nTotal number of variables............................:        2\n                     variables with only lower bounds:        0\n                variables with lower and upper bounds:        0\n                     variables with only upper bounds:        0\nTotal number of equality constraints.................:        0\nTotal number of inequality constraints...............:        0\n        inequality constraints with only lower bounds:        0\n   inequality constraints with lower and upper bounds:        0\n        inequality constraints with only upper bounds:        0\n\niter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls\n   0  1.0000000e+00 0.00e+00 2.00e+00   0.0 0.00e+00    -  0.00e+00 0.00e+00   0\n   1  9.5312500e-01 0.00e+00 1.25e+01 -11.0 1.00e+00    -  1.00e+00 2.50e-01f  3\n   2  4.8320569e-01 0.00e+00 1.01e+00 -11.0 9.03e-02    -  1.00e+00 1.00e+00f  1\n   3  4.5708829e-01 0.00e+00 9.53e+00 -11.0 4.29e-01    -  1.00e+00 5.00e-01f  2\n   4  1.8894205e-01 0.00e+00 4.15e-01 -11.0 9.51e-02    -  1.00e+00 1.00e+00f  1\n   5  1.3918726e-01 0.00e+00 6.51e+00 -11.0 3.49e-01    -  1.00e+00 5.00e-01f  2\n   6  5.4940990e-02 0.00e+00 4.51e-01 -11.0 9.29e-02    -  1.00e+00 1.00e+00f  1\n   7  2.9144630e-02 0.00e+00 2.27e+00 -11.0 2.49e-01    -  1.00e+00 5.00e-01f  2\n   8  9.8586451e-03 0.00e+00 1.15e+00 -11.0 1.10e-01    -  1.00e+00 1.00e+00f  1\n   9  2.3237475e-03 0.00e+00 1.00e+00 -11.0 1.00e-01    -  1.00e+00 1.00e+00f  1\niter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls\n  10  2.3797236e-04 0.00e+00 2.19e-01 -11.0 5.09e-02    -  1.00e+00 1.00e+00f  1\n  11  4.9267371e-06 0.00e+00 5.95e-02 -11.0 2.53e-02    -  1.00e+00 1.00e+00f  1\n  12  2.8189505e-09 0.00e+00 8.31e-04 -11.0 3.20e-03    -  1.00e+00 1.00e+00f  1\n  13  1.0095040e-15 0.00e+00 8.68e-07 -11.0 9.78e-05    -  1.00e+00 1.00e+00f  1\n  14  1.3288608e-28 0.00e+00 2.02e-13 -11.0 4.65e-08    -  1.00e+00 1.00e+00f  1\n\nNumber of Iterations....: 14\n\n                                   (scaled)                 (unscaled)\nObjective...............:   1.3288608467480825e-28    1.3288608467480825e-28\nDual infeasibility......:   2.0183854587685121e-13    2.0183854587685121e-13\nConstraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00\nVariable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00\nComplementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00\nOverall NLP error.......:   2.0183854587685121e-13    2.0183854587685121e-13\n\n\nNumber of objective function evaluations             = 36\nNumber of objective gradient evaluations             = 15\nNumber of equality constraint evaluations            = 0\nNumber of inequality constraint evaluations          = 0\nNumber of equality constraint Jacobian evaluations   = 0\nNumber of inequality constraint Jacobian evaluations = 0\nNumber of Lagrangian Hessian evaluations             = 14\nTotal seconds in IPOPT                               = 0.026\n\nEXIT: Optimal Solution Found.\n      solver  :   t_proc      (avg)   t_wall      (avg)    n_eval\n       nlp_f  |   1.42ms ( 39.56us) 239.45us (  6.65us)        36\n  nlp_grad_f  | 569.00us ( 35.56us) 110.70us (  6.92us)        16\n  nlp_hess_l  | 693.00us ( 49.50us) 160.27us ( 11.45us)        14\n       total  | 199.18ms (199.18ms)  26.87ms ( 26.87ms)         1\n```\n:::\n:::\n\n\n\n\nThe solver prints a progress log as it works. For now, only the last lines matter: `EXIT: Optimal Solution Found` means the solver converged to a point satisfying the optimality conditions, and the timing table shows the entire solve took milliseconds (re-timing this solve on this machine gives about 25 ms, in 14 iterations). We'll learn to read the rest of this log — and what to do when it *doesn't* say \"Optimal Solution Found\" — in @sec-solvers-and-solutions.\n\nNote two things about the code. First, `rosenbrock()` is an ordinary Python function, written before `opti` existed — you can organize your models with functions and classes as usual, and pass optimization variables through them. Second, extracting answers uses `sol(...)`, which evaluates *any* expression at the optimum, not just bare variables:\n\n::: {#eceb54d6 .cell execution_count=5}\n``` {.python .cell-code}\nprint(f\"x = {sol(x)}\")\nprint(f\"y = {sol(y)}\")\nprint(f\"objective = {sol(rosenbrock(x, y))}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nx = 0.9999999999999899\ny = 0.9999999999999792\nobjective = 1.3288608467480825e-28\n```\n:::\n:::\n\n\nThe solver lands on $(1, 1)$ to machine precision, matching the hand calculation.\n\n::: {.callout-note}\n## Initial guesses\n\n`init_guess` tells the optimizer where to start looking. For this small problem almost any start works, but for large nonconvex problems the quality of your initial guess strongly affects both solve time and *which* local optimum you find. Get in the habit of providing physically-sensible guesses.\n:::\n\n## Adding a constraint {#sec-optimization-basics-constraints}\n\nReal design problems are constrained, so let's constrain this one: **find the lowest point of the Rosenbrock valley that lies within the unit circle**, i.e. subject to $x^2 + y^2 \\le 1$. The unconstrained minimum at $(1, 1)$ has a radius of $\\sqrt{2}$, so it's no longer feasible — we expect the new optimum to sit *on* the circle, somewhere down-valley of $(1, 1)$.\n\nConstraints are declared with `opti.subject_to()`, using natural comparison syntax. We'll also start the solver at $(-1.5, 1.5)$ — deliberately *outside* the feasible circle — to make a point: **initial guesses do not need to be feasible.** IPOPT drives infeasibility to zero as it converges.\n\nOne new trick here: `opti.solve()` accepts a `callback` function that runs at every solver iteration. Inside it, `opti.debug.value(...)` reads the current (not-yet-converged) value of any expression — ideal for recording the optimizer's path so we can watch it think:\n\n::: {#cbf6477f .cell execution_count=6}\n``` {.python .cell-code}\nopti = asb.Opti()\n\nx = opti.variable(init_guess=-1.5)\ny = opti.variable(init_guess=1.5)  # Note: (-1.5, 1.5) is infeasible. That's fine.\n\nopti.minimize(rosenbrock(x, y))\n\nopti.subject_to(x**2 + y**2 <= 1)  # Constrain the design to the unit disk\n\niterates = []  # Record the optimizer's path, for plotting\n\nsol = opti.solve(\n    callback=lambda iteration: iterates.append(\n        (opti.debug.value(x), opti.debug.value(y))\n    ),\n    verbose=False,  # Suppresses the IPOPT log we saw earlier\n)\n\nx_star, y_star = sol(x), sol(y)\nr_star = sol((x**2 + y**2) ** 0.5)\nprint(f\"Optimum: x = {x_star:.6f}, y = {y_star:.6f}, radius = {r_star:.6f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOptimum: x = 0.786415, y = 0.617698, radius = 1.000000\n```\n:::\n:::\n\n\n::: {#cell-fig-01-constrained-path .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![The optimizer's path on the constrained Rosenbrock problem. Starting from an infeasible guess, IPOPT steps into the feasible disk, finds the valley floor, and follows it until the constraint stops it.](01-optimization-basics_files/figure-html/fig-01-constrained-path-output-1.png){#fig-01-constrained-path width=942 height=711 fig-alt='Contour plot of the Rosenbrock function with the feasible unit disk shaded gray. A blue line with dots traces the optimizer iterates from the infeasible initial guess at (-1.5, 1.5) into the disk and along the valley to the constrained optimum on the circle boundary, marked with a star. The unconstrained minimum at (1, 1) is shown grayed out outside the circle.'}\n:::\n:::\n\n\nThe optimum lands at (0\\.786, 0\\.618), and its radius is 1\\.000000 — the constraint is *active* (tight) at the solution, exactly as the geometry suggested. The whole 18-iteration solve, path recording included, still takes milliseconds. (If you wanted to certify this optimum by hand, you'd verify the [KKT conditions](https://en.wikipedia.org/wiki/Karush%E2%80%93Kuhn%E2%80%93Tucker_conditions); for now, we'll trust the optimizer's convergence test, which checks exactly that.)\n\nA few practical notes on constraints:\n\n* **Strict vs. non-strict inequalities are the same thing here.** Numerically, there's no difference between `<` and `<=` (or `>` and `>=`) — use whichever reads better.\n* **Equality constraints use `==`.** For example, `opti.subject_to(lift == weight)` is the standard way to close a steady-flight force balance — you'll see this constantly from @sec-wing-design onward.\n* **You can pass a list.** `opti.subject_to([x >= 0, x <= 5])` declares both constraints at once; this often makes model code read like a specification.\n* **Declaration order is free.** Variables, constraints, and the objective can be declared in any order, as long as everything is in place before `opti.solve()`.\n* **`opti.maximize(f)` exists too** — it's simply sugar for `opti.minimize(-f)`.\n\n## Vectorized variables {#sec-optimization-basics-vectorized}\n\nDeclaring variables one at a time stops scaling long before real problems do — a trajectory optimization might need the aircraft's altitude at 100 points in time. Rule #1 of scientific Python applies to optimization too: **vectorize everything.** `opti.variable()` creates a whole vector of decision variables when you hand it a vector initial guess.\n\nThe standard benchmark here is the $N$-dimensional sphere problem — words first: find the point closest to the origin, where \"closeness\" is the sum of squared coordinates. As math:\n\n$$ \\underset{\\vec{x}}{\\text{minimize}} \\quad \\sum_{i=1}^{N} x_i^2 $$\n\nLet's solve it in 100-dimensional space:\n\n::: {#06db5e49 .cell execution_count=8}\n``` {.python .cell-code}\nimport aerosandbox.numpy as np  # More on this import in the next section!\n\nN = 100\n\nopti = asb.Opti()\n\nx = opti.variable(init_guess=np.ones(N))  # A vector variable: length inferred\n                                          # from the initial guess.\nopti.minimize(np.sum(x**2))\n\nsol = opti.solve(verbose=False)\n\nprint(f\"Number of variables:  {N}\")\nprint(f\"Solver iterations:    {sol.stats()['iter_count']}\")\nprint(f\"Max |x_i| at optimum: {np.max(np.abs(sol(x))):.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of variables:  100\nSolver iterations:    1\nMax |x_i| at optimum: 0.00e+00\n```\n:::\n:::\n\n\nAll 100 components go to zero — in a *single* solver iteration. That's no accident: the sphere problem is an unconstrained quadratic, and IPOPT is a second-order (Newton-type) method, so one full Newton step lands exactly on the optimum. This is a recurring theme: modern solvers exploit curvature information, and (as we'll see next) AeroSandbox supplies exact second derivatives automatically.\n\nVector variables really shine because **constraints broadcast element-wise**, just like NumPy arithmetic. One `subject_to()` call below creates 100 constraints — a per-element lower bound $x_i \\ge b_i$:\n\n::: {#83e21691 .cell execution_count=9}\n``` {.python .cell-code}\nb = np.linspace(-1, 1, N)  # A different lower bound for each element\n\nopti = asb.Opti()\nx = opti.variable(init_guess=np.ones(N))\nopti.subject_to(x >= b)  # 100 constraints in one line\nopti.minimize(np.sum(x**2))\n\nsol = opti.solve(verbose=False)\nx_opt = sol(x)\n```\n:::\n\n\n::: {#cell-fig-01-vector-bounds .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Solution of the bounded sphere problem. Where the lower bound is negative, the optimizer parks each element at its unconstrained optimum of zero; where the bound is positive, the constraint is active and the element sits exactly on it.](01-optimization-basics_files/figure-html/fig-01-vector-bounds-output-1.png){#fig-01-vector-bounds width=1203 height=495 fig-alt='Line plot versus variable index from 0 to 99. A gray dashed line shows the lower bound rising linearly from -1 to 1. A blue line shows the optimal solution: zero for the first half of indices, then following the bound exactly for the second half.'}\n:::\n:::\n\n\nThe result reads like a textbook illustration of constrained optimality: each element independently settles at $\\max(b_i,\\, 0)$. Where the bound doesn't bind, the optimizer ignores it; where it does, the solution sits exactly on it.\n\nMore syntax you'll use constantly:\n\n* **Scalar guess, explicit length:** `opti.variable(init_guess=1, n_vars=N)` is shorthand for a length-`N` vector with every element initialized to 1. Use the array form (`init_guess=np.linspace(...)`) when elements should start at different values — for trajectory problems, a straight-line guess between endpoints is a great default.\n* **Indexing works:** `x[3]`, `x[10:20]`, and friends behave as you'd expect, so you can constrain, say, boundary conditions: `opti.subject_to(x[0] == 0)`.\n* **Dimensionality:** scalars and 1D vectors cover nearly all engineering design problems; 2D matrix variables are supported, but higher-dimensional arrays of *decision variables* are not (plain `aerosandbox.numpy` math on numeric arrays has no such limit).\n\n## Why `aerosandbox.numpy` exists {#sec-optimization-basics-numpy}\n\nYou may have noticed the import `import aerosandbox.numpy as np` above and wondered why we don't just use NumPy. The short answer: **so that the solver can differentiate your code.**\n\nHere's the chain of reasoning. IPOPT is a gradient-based optimizer: at every iteration it needs derivatives of the objective and every constraint with respect to every variable — including exact second derivatives, which is how the sphere problem solved in one Newton step. Computing those by finite differences would be slow and noisy; deriving them by hand, for an entire aircraft model, would be unthinkable. Instead, CasADi uses [automatic differentiation](https://en.wikipedia.org/wiki/Automatic_differentiation) (AD): when you write `rosenbrock(x, y)` with opti variables, no arithmetic actually happens — instead, a symbolic *trace* (a directed graph of every `+`, `*`, `cos`, `exp`, ...) is recorded, and exact derivatives of the whole graph come almost for free. This is why an `opti` variable prints as a symbolic `MX` object rather than a number.\n\nThe catch: every operation between variable and objective must be *traceable*. Plain NumPy functions don't know what a CasADi `MX` object is, so they would break the trace (or crash). Rewriting your math in CasADi's own syntax would work, but then your model code couldn't be run on ordinary numbers. AeroSandbox resolves this with a **dual-backend NumPy**: `aerosandbox.numpy` re-exports all of NumPy, and re-implements the functions that need it so that each one dispatches on its input type —\n\n* **NumPy arrays in → NumPy arrays out**, with identical behavior and speed to stock NumPy;\n* **Optimization variables in → traced symbolic expressions out**, keeping the AD graph intact.\n\nSo the practice is simply: **in any code that might ever touch an optimization variable, write `import aerosandbox.numpy as np` instead of `import numpy as np`** — and then write your engineering models once, use them everywhere. Let's see the dispatch in action with `np.where`, the vectorized if/else:\n\n::: {#11b25ecb .cell execution_count=11}\n``` {.python .cell-code}\nimport aerosandbox.numpy as np\n\n# Numeric inputs: behaves exactly like numpy.where...\nvalues = np.linspace(0, 4, 5)\nprint(np.where(values > 2, values, 0.0))\nprint(type(np.where(values > 2, values, 0.0)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[0. 0. 0. 3. 4.]\n<class 'numpy.ndarray'>\n```\n:::\n:::\n\n\n::: {#c00e0e3d .cell execution_count=12}\n``` {.python .cell-code}\n# ...symbolic inputs: builds a traceable expression instead.\nopti = asb.Opti()\nv = opti.variable(init_guess=1)\n\nexpression = np.where(v > 2, v, 0.0)\nprint(type(expression))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'casadi.casadi.MX'>\n```\n:::\n:::\n\n\nSame function, same call signature — a NumPy `ndarray` in the first case, a symbolic CasADi `MX` node in the second. Every AeroSandbox physics model is built out of functions like this, which is why the same drag model can be evaluated on a plain float for a quick check *and* optimized through with exact gradients.\n\n`aerosandbox.numpy` also adds functions stock NumPy doesn't have, purpose-built for optimization. A favorite is `np.softmax` — a smooth, differentiable stand-in for `max()`. It's worth a picture: the hard maximum has a kink where the two arguments cross, and gradient-based optimizers handle kinks badly. `softmax` rounds the kink off, with a `softness` parameter (in the same units as the inputs) setting how much discrepancy between the inputs is \"physically significant\":\n\n::: {#ff9649e1 .cell execution_count=13}\n``` {.python .cell-code}\nt = np.linspace(-2, 2, 300)\nhard = np.maximum(t, 0)\nsoft = np.softmax(t, 0, softness=0.4)  # Works on arrays...\nprint(f\"softmax(3, 4) = {np.softmax(3, 4, softness=0.4):.4f}\")  # ...and scalars.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsoftmax(3, 4) = 4.0316\n```\n:::\n:::\n\n\n::: {#cell-fig-01-softmax .cell execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![The hard maximum has a kink at the crossover; softmax rounds it off so gradient-based optimizers always see smooth curvature.](01-optimization-basics_files/figure-html/fig-01-softmax-output-1.png){#fig-01-softmax width=921 height=495 fig-alt='Line plot of f(x) versus x from -2 to 2. A gray line shows max(x, 0) with a sharp corner at the origin. A blue line shows softmax(x, 0) with softness 0.4, which follows the same asymptotes but curves smoothly through the corner region.'}\n:::\n:::\n\n\nAnd because `np.softmax` is smooth and traceable, you can optimize straight through it — here, finding the point where two crossing lines have the lowest \"soft-maximum\", a miniature of the min-max problems that appear constantly in design (e.g., minimizing the *worst-case* drag across flight conditions):\n\n::: {#069cbea4 .cell execution_count=15}\n``` {.python .cell-code}\nopti = asb.Opti()\nv = opti.variable(init_guess=3)\n\nworst_case = np.softmax(v, 2 - v, softness=0.5)  # Smooth max of two functions\nopti.minimize(worst_case)\n\nsol = opti.solve(verbose=False)\nprint(f\"v = {sol(v):.4f}, worst-case value = {sol(worst_case):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nv = 1.0000, worst-case value = 1.3466\n```\n:::\n:::\n\n\nThe optimizer settles at v = 1\\.00, right at the crossover — precisely where a hard `max()` would have a non-differentiable kink and stall a naive formulation. (The full playbook of such reformulation tricks — and the sharp edges of `np.where`, which is traceable but still kinked — is the subject of @sec-robust-optimization-models.)\n\nThe catalog of traceable operations is extensive: trigonometry, logarithms, interpolation, norms, linear solves, and more. Not every obscure NumPy function has been overloaded, though — if something you need is missing, check `aerosandbox/numpy/test_numpy/test_all_operations_run.py` for what's supported, and [open an issue](https://github.com/peterdsharpe/AeroSandbox/issues) for what isn't.\n\n## Where to go next {#sec-optimization-basics-next}\n\nYou now have the complete `Opti` vocabulary: `variable` / `subject_to` / `minimize` / `solve` / `sol()`, vectorized, with `aerosandbox.numpy` keeping everything differentiable. Three good directions from here:\n\n* @sec-robust-optimization-models teaches the modeling patterns that keep real problems solvable — continuity and differentiability tricks, NaN-proofing, and problem scaling. Read it before writing your first serious model; it's the difference between solves that converge and solves that mysteriously don't.\n* @sec-solvers-and-solutions goes deeper on the solve itself: reading IPOPT's output, solver options, parameter sweeps, and extracting sensitivities (dual variables) from a converged solution.\n* Impatient for airplanes? @sec-wing-design applies exactly the machinery from this chapter to a real wing design problem — including a cautionary tale about what optimizers do to under-constrained models.\n\n",
    "supporting": [
      "01-optimization-basics_files"
    ],
    "filters": [],
    "includes": {}
  }
}