{
  "hash": "718e6b53c69bc0226f89bbf1212733eb",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nexecute:\n  warning: false\n---\n\n# Aircraft Sizing: SimPleAC {#sec-aircraft-sizing-simpleac}\n\nIn this chapter, we size a complete airplane — aerodynamics, wing structure, fuel volume, and mission performance, all coupled — in about 40 lines of model code that solve in milliseconds. Along the way you'll learn the single most underrated feature of optimization-native design: because the optimizer carries exact derivative information, you get the *sensitivity of your objective to every requirement and technology assumption* essentially for free, without re-solving anything. We close by cross-checking the optimum against a published geometric-programming (GP) solution of the same problem, and by sweeping the design across a 12× range of missions.\n\nIf the previous chapter ([Wing Design](09-wing-design.qmd)) was about making a single discipline push back, this chapter is about *closure*: making a whole vehicle's weights, aerodynamics, and mission consistent with each other at the optimum.\n\n## The SimPleAC problem {#sec-simpleac-problem}\n\nThe design brief: a small piston-engine airplane must carry a fixed useful load of 6,250 N (airframe-minus-wing, engine, and payload together) over a 1,000 km mission, and it must be able to take off and land at no more than 25 m/s. Everything else — how big the wing is, how slender it is, how fast to cruise, how much fuel to carry, and where to put that fuel — is up to the optimizer. The objective is to burn as little fuel as possible.\n\nThis problem is called **SimPleAC** (\"Simple Aircraft\"), proposed by Warren Hoburg and refined in Berk Öztürk's [MIT Master's thesis](https://dspace.mit.edu/handle/1721.1/115595). It was created as a showcase for geometric programming via [GPKit](https://github.com/convexengineering/gpkit), and the reference implementation lives in [GPLibrary](https://github.com/convexengineering/gplibrary/tree/master/gpkitmodels/SP/SimPleAC). That pedigree makes it a perfect validation case: a GP solver computes a *certified global optimum* for this problem, so we can check AeroSandbox's general-purpose automatic-differentiation (AD) approach against a known answer — and then go beyond what GP can express.\n\nThe physics couples in a loop that should feel familiar from any aircraft design text:\n\n- A bigger mission needs more **fuel**, which adds weight.\n- More weight needs more **lift**, hence more wing area or speed — but the landing-speed requirement pins the wing area to the weight.\n- More wing area and span add **drag and structural weight**, which... burns more fuel.\n\nSizing means finding the fixed point of this loop, *and* choosing the free parameters (aspect ratio, cruise speed, fuel placement) to make that fixed point as cheap as possible. In an optimization framework, we don't iterate the loop manually — we just state all the couplings as constraints and let the optimizer close them simultaneously.\n\n## The model {#sec-simpleac-model}\n\nWe begin by creating an optimization environment:\n\n::: {#0d8bd716 .cell execution_count=1}\n``` {.python .cell-code}\nimport aerosandbox as asb\nimport aerosandbox.numpy as np\nimport aerosandbox.tools.units as u\n\nopti = asb.Opti()\n```\n:::\n\n\n### Constants, as parameters\n\nNext, the fixed inputs. We declare each one as an `opti.parameter()` rather than a plain Python float. For *solving*, the two are interchangeable — a parameter is just a constant the optimizer never touches. The payoff comes later, in @sec-simpleac-sensitivities: declaring inputs as parameters lets us extract the sensitivity of the optimum to every one of them after the solve, at negligible cost. All values are in base SI units.\n\n::: {#cb7ac957 .cell execution_count=2}\n``` {.python .cell-code}\n### Environment\ng     = opti.parameter(value=9.81)      # gravitational acceleration [m/s^2]\nmu    = opti.parameter(value=1.775e-5)  # air viscosity [kg/m/s]\nrho   = opti.parameter(value=1.23)      # air density [kg/m^3]\nrho_f = opti.parameter(value=817)       # fuel density [kg/m^3]\n\n### Technology assumptions (non-dimensional)\nC_Lmax     = opti.parameter(value=1.6)    # max C_L, flaps down [-]\ne          = opti.parameter(value=0.92)   # Oswald efficiency factor [-]\nk          = opti.parameter(value=1.17)   # form factor [-]\nN_ult      = opti.parameter(value=3.3)    # ultimate load factor [-]\nS_wetratio = opti.parameter(value=2.075)  # wetted area / reference area [-]\ntau        = opti.parameter(value=0.12)   # airfoil thickness-to-chord ratio [-]\nW_W_coeff1 = opti.parameter(value=2e-5)   # wing weight coefficient 1 [1/m]\nW_W_coeff2 = opti.parameter(value=60)     # wing weight coefficient 2 [Pa]\n\n### Requirements\nRange = opti.parameter(value=1000e3)      # mission range [m]\nTSFC  = opti.parameter(value=0.6 / u.hour)  # thrust-specific fuel consumption [1/s]\nV_min = opti.parameter(value=25)          # takeoff / landing speed limit [m/s]\nW_0   = opti.parameter(value=6250)        # fixed weight: everything but wing & fuel [N]\n```\n:::\n\n\n### Design variables\n\nSeven quantities are free. Each gets an order-of-magnitude initial guess from engineering intuition (these were chosen *before* looking at the answer — a cruise-speed guess of 100 m/s turns out to be almost 2× too fast, and it doesn't matter).\n\n::: {#cfb77f52 .cell execution_count=3}\n``` {.python .cell-code}\nAR       = opti.variable(init_guess=10,    scale=10,    log_transform=True)  # aspect ratio [-]\nS        = opti.variable(init_guess=10,    scale=10,    log_transform=True)  # wing area [m^2]\nV        = opti.variable(init_guess=100,   scale=100,   log_transform=True)  # cruise speed [m/s]\nW        = opti.variable(init_guess=10000, scale=10000, log_transform=True)  # gross weight [N]\nC_L      = opti.variable(init_guess=1,     scale=1,     log_transform=True)  # cruise lift coefficient [-]\nW_f      = opti.variable(init_guess=3000,  scale=3000,  log_transform=True)  # fuel weight [N]\nV_f_fuse = opti.variable(init_guess=1,     scale=1,     log_transform=True)  # fuselage fuel volume [m^3]\n```\n:::\n\n\nTwo modeling choices here deserve a comment (both are covered in depth in [Building Robust Optimization Models](02-robust-optimization-models.qmd)):\n\n* **`log_transform=True`** makes the solver work with $\\ln x$ instead of $x$. Every one of these quantities is physically positive and appears in power-law-type relations, so log-space is their natural habitat: positivity is enforced automatically, and the singularity at zero (e.g., $Re \\to 0$ in the skin-friction model, or $AR \\to 0$ giving zero span) can never be visited.\n* **`scale=` equal to the initial guess** makes the solver-facing log variable exactly $\\ln x$, i.e., unit-scaled — a step of 1 in solver space means an $e$-fold change in the physical quantity, for every variable. This costs nothing to write and measurably improves solver robustness, which will matter when we sweep this problem over a wide parameter range in @sec-simpleac-sweeps.\n\nCompared to the original GPKit formulation, we also silently dropped several \"free variables\" (`Re`, `C_f`, `C_D`, `D`, `L/D`, `T_flight`, ...) that don't need to be decision variables at all — they're explicit functions of the seven above, so we'll simply compute them. Same engineering problem, simpler notation, smaller problem for the solver.\n\n### Weights and lift\n\nThe wing's weight has two parts. The *skin* weight scales with wing area. The *structural* (bending) weight grows steeply with aspect ratio — a slender wing is a long lever arm — and with the square root of the product of the loads it must carry: the weight sized by the gust/maneuver load ($W$, through the ultimate load factor $N_\\mathrm{ult}$) and the weight providing inertial relief. In symbols:\n\n$$\nW_w =\n\\underbrace{W_{W,2} \\, S \\vphantom{\\frac{W}{\\tau}}}_{\\text{skin}}\n\\;+\\;\n\\underbrace{\\frac{W_{W,1}}{\\tau} \\, N_\\mathrm{ult} \\, A\\!R^{3/2} \\sqrt{\\left(W_0 + \\rho_f g V_{f,\\mathrm{fuse}}\\right) W \\, S}}_{\\text{bending structure}}\n$$\n\nNote the appearance of $\\rho_f g V_{f,\\mathrm{fuse}}$: fuel stored in the *fuselage* adds to the load the wing root must carry, whereas fuel stored in the *wing* provides bending relief. This term is what will make the fuel-placement trade interesting.\n\nThree constraints tie weights to lift:\n\n1. **Weight closure**: gross weight covers fixed weight, wing weight, and fuel.\n2. **Cruise lift**: lift equals weight at the mid-cruise point (half the fuel burned).\n3. **Landing**: at gross weight, the wing must be able to fly at `V_min` with flaps down — this is what forces the wing to be big.\n\n::: {#1d424442 .cell execution_count=4}\n``` {.python .cell-code}\nW_w_surf = W_W_coeff2 * S\nW_w_strc = (\n    W_W_coeff1 / tau * N_ult * AR**1.5\n    * np.sqrt((W_0 + V_f_fuse * rho_f * g) * W * S)\n)\nW_w = W_w_surf + W_w_strc\n\nopti.subject_to([\n    W >= W_0 + W_w + W_f,                                 # weight closure\n    W_0 + W_w + 0.5 * W_f <= 0.5 * rho * S * C_L * V**2,  # cruise lift, mid-fuel\n    W <= 0.5 * rho * S * C_Lmax * V_min**2,               # stall at landing speed\n])\n```\n:::\n\n\n### Drag and fuel burn\n\nDrag has three contributions: fuselage form drag (proportional to a drag area $CDA_0$), wing profile drag (turbulent flat-plate skin friction with a form factor), and induced drag. A modeling quirk inherited from SimPleAC: the fuselage drag area is tied to the fuselage fuel volume, $CDA_0 = V_{f,\\mathrm{fuse}} / 10\\,\\mathrm{m}$ — a bigger belly tank means a fatter, draggier fuselage. So fuselage fuel costs drag, and wing fuel costs nothing aerodynamically — but wing volume is limited by the wing's own geometry. The optimizer will have to balance these.\n\nFuel burn comes from cruising a distance `Range` at speed $V$ with drag $D$ and a thrust-specific fuel consumption `TSFC`:\n\n$$\nW_f \\geq \\mathrm{TSFC} \\cdot \\underbrace{\\frac{\\mathrm{Range}}{V}}_{\\text{flight time}} \\cdot \\, D\n$$\n\nThis is the Breguet range relation, linearized by evaluating drag at the mid-cruise weight (the `0.5 * W_f` in the lift constraint above). For fuel fractions this small the approximation is excellent, and it keeps the model algebraic.\n\n::: {#02a65577 .cell execution_count=5}\n``` {.python .cell-code}\nRe  = (rho / mu) * V * np.sqrt(S / AR)  # Reynolds number at mean chord\nC_f = 0.074 / Re**0.2                   # turbulent flat-plate skin friction\n\nCDA0 = V_f_fuse / 10                    # fuselage drag area [m^2]\n\nC_D_fuse = CDA0 / S                     # fuselage\nC_D_wpar = k * C_f * S_wetratio         # wing profile\nC_D_ind  = C_L**2 / (np.pi * AR * e)    # induced\nC_D = C_D_fuse + C_D_wpar + C_D_ind\n\nD = 0.5 * rho * V**2 * S * C_D\n\nT_flight = Range / V\n\nopti.subject_to(W_f >= TSFC * T_flight * D)\n```\n:::\n\n\n### Fuel volume\n\nThe fuel has to physically fit somewhere: in the wing box or in the fuselage tank. The wing's available volume scales like span × chord × airfoil thickness, i.e., linearly in span and thickness and quadratically in chord, which works out to $S^{1.5} A\\!R^{-0.5} \\tau$:\n\n::: {#52a58c0d .cell execution_count=6}\n``` {.python .cell-code}\nV_f = W_f / (g * rho_f)                        # required tank volume [m^3]\nV_f_wing = 0.03 * S**1.5 / np.sqrt(AR) * tau   # volume available in wing box [m^3]\n\nopti.subject_to(V_f_wing + V_f_fuse >= V_f)\n```\n:::\n\n\n### Solve\n\nThat's the whole airplane. Minimize fuel and solve:\n\n::: {#24e116ac .cell execution_count=7}\n``` {.python .cell-code}\nopti.minimize(W_f)\n\nsol = opti.solve(max_iter=100)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThis is Ipopt version 3.14.11, running with linear solver MUMPS 5.4.1.\n\nNumber of nonzeros in equality constraint Jacobian...:        0\nNumber of nonzeros in inequality constraint Jacobian.:       24\nNumber of nonzeros in Lagrangian Hessian.............:       19\n\nTotal number of variables............................:        7\n                     variables with only lower bounds:        0\n                variables with lower and upper bounds:        0\n                     variables with only upper bounds:        0\nTotal number of equality constraints.................:        0\nTotal number of inequality constraints...............:        5\n        inequality constraints with only lower bounds:        0\n   inequality constraints with lower and upper bounds:        0\n        inequality constraints with only upper bounds:        5\n\niter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls\n   0  3.0000000e+03 3.85e+03 5.89e+01   0.0 0.00e+00    -  0.00e+00 0.00e+00   0\n   1  1.6617064e+03 1.68e+03 1.79e+02  -1.2 7.11e-01   2.0 9.92e-01 1.00e+00f  1\n   2  2.4552629e+03 3.57e+02 3.99e+01  -0.9 8.16e-01   1.5 1.00e+00 8.79e-01h  1\n   3  2.7647196e+03 4.96e+00 7.08e+00  -0.7 2.52e-01   1.0 1.00e+00 1.00e+00h  1\n   4  2.7097731e+03 0.00e+00 9.62e+00  -2.6 2.78e-01   0.6 1.00e+00 5.78e-01f  1\n   5  2.6705232e+03 1.70e-01 1.06e+00  -2.6 8.62e-01   0.1 1.00e+00 9.48e-01f  1\n   6  2.6077879e+03 9.17e-01 1.08e+00  -3.0 2.63e+00  -0.4 1.00e+00 7.38e-01f  1\n   7  2.3511820e+03 1.34e+01 1.14e+00  -5.2 8.29e+00  -0.9 1.00e+00 1.00e+00f  1\n   8  1.4833379e+03 2.10e+02 1.94e+00 -10.2 3.15e+01  -1.3 1.00e+00 9.85e-01f  1\n   9  1.4627473e+03 2.07e+02 3.29e+01  -3.2 2.02e+01  -0.9 1.00e+00 1.54e-02f  1\niter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls\n  10  1.4619769e+03 2.07e+02 1.06e+01  -3.2 2.11e+00    -  1.00e+00 1.47e-03h  1\n  11  1.0909687e+03 9.13e+01 1.91e+00  -5.3 4.18e-01    -  1.00e+00 1.00e+00f  1\n  12  9.5942303e+02 2.02e+01 7.97e-01  -5.8 2.46e-01    -  1.00e+00 1.00e+00f  1\n  13  9.3832026e+02 9.58e-01 6.02e-02  -7.4 6.53e-02    -  1.00e+00 1.00e+00h  1\n  14  9.3775634e+02 1.67e-03 1.27e-04  -9.1 3.28e-03    -  1.00e+00 1.00e+00h  1\n  15  9.3775596e+02 5.86e-10 2.45e-10 -11.0 6.59e-06    -  1.00e+00 1.00e+00h  1\n\nNumber of Iterations....: 15\n\n                                   (scaled)                 (unscaled)\nObjective...............:   3.1258531841321052e+01    9.3775595523963079e+02\nDual infeasibility......:   2.4453328251183848e-10    7.3359984753551486e-09\nConstraint violation....:   8.2564139401092708e-12    5.8560883393511031e-10\nVariable bound violation:   0.0000000000000000e+00    0.0000000000000000e+00\nComplementarity.........:   1.0000306005617723e-11    3.0000918016853143e-10\nOverall NLP error.......:   2.4453328251183848e-10    7.3359984753551486e-09\n\n\nNumber of objective function evaluations             = 16\nNumber of objective gradient evaluations             = 16\nNumber of equality constraint evaluations            = 0\nNumber of inequality constraint evaluations          = 16\nNumber of equality constraint Jacobian evaluations   = 0\nNumber of inequality constraint Jacobian evaluations = 16\nNumber of Lagrangian Hessian evaluations             = 15\nTotal seconds in IPOPT                               = 0.041\n\nEXIT: Optimal Solution Found.\n      solver  :   t_proc      (avg)   t_wall      (avg)    n_eval\n       nlp_f  |   1.24ms ( 77.31us) 139.53us (  8.72us)        16\n       nlp_g  |   8.03ms (501.81us) 757.16us ( 47.32us)        16\n  nlp_grad_f  |   2.09ms (123.00us) 235.89us ( 13.88us)        17\n  nlp_hess_l  |  14.38ms (959.00us)   1.67ms (111.66us)        15\n   nlp_jac_g  |  10.45ms (615.00us)   1.12ms ( 65.76us)        17\n       total  | 413.18ms (413.18ms)  42.65ms ( 42.65ms)         1\n```\n:::\n:::\n\n\nIPOPT closes the entire coupled sizing loop in 15 iterations — note the `Total seconds in IPOPT` line above: the solve itself takes a few tens of milliseconds. (The first call to `opti.solve()` also spends a moment building and compiling the computational graph; re-solves at new parameter values skip that and run at nearly the raw IPOPT speed, which we'll exploit shortly.)\n\n## The optimal airplane {#sec-simpleac-results}\n\nLet's see what the optimizer designed:\n\n::: {#3c9023bb .cell execution_count=8}\n``` {.python .cell-code}\nb = np.sqrt(AR * S)  # wingspan [m]\n\nprint(\"Design variables:\")\nfor name, x, unit in [\n    (\"Aspect ratio\",         AR,       \"-\"),\n    (\"Wing area\",            S,        \"m^2\"),\n    (\"Cruise speed\",         V,        \"m/s\"),\n    (\"Gross weight\",         W,        \"N\"),\n    (\"Cruise C_L\",           C_L,      \"-\"),\n    (\"Fuel weight\",          W_f,      \"N\"),\n    (\"Fuselage fuel volume\", V_f_fuse, \"m^3\"),\n]:\n    print(f\"    {name:22s} = {sol(x):10.4g} {unit}\")\n\nprint(\"Derived quantities:\")\nfor name, x, unit in [\n    (\"Wingspan\",             b,               \"m\"),\n    (\"Gross mass\",           W / g,           \"kg\"),\n    (\"Fuel fraction\",        W_f / W,         \"-\"),\n    (\"Wing weight\",          W_w,             \"N\"),\n    (\"  ...structural part\", W_w_strc,        \"N\"),\n    (\"Cruise L/D\",           C_L / C_D,       \"-\"),\n    (\"Cruise Reynolds no.\",  Re,              \"-\"),\n    (\"Drag\",                 D,               \"N\"),\n    (\"Flight time\",          T_flight / u.hour, \"hr\"),\n    (\"Wing fuel volume\",     V_f_wing,        \"m^3\"),\n    (\"Total fuel volume\",    V_f,             \"m^3\"),\n]:\n    print(f\"    {name:22s} = {sol(x):10.4g} {unit}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDesign variables:\n    Aspect ratio           =       12.1 -\n    Wing area              =      14.15 m^2\n    Cruise speed           =      57.11 m/s\n    Gross weight           =       8705 N\n    Cruise C_L             =     0.2901 -\n    Fuel weight            =      937.8 N\n    Fuselage fuel volume   =     0.0619 m^3\nDerived quantities:\n    Wingspan               =      13.09 m\n    Gross mass             =      887.3 kg\n    Fuel fraction          =     0.1077 -\n    Wing weight            =       1517 N\n      ...structural part   =      667.8 N\n    Cruise L/D             =      25.63 -\n    Cruise Reynolds no.    =  4.279e+06 -\n    Drag                   =      321.3 N\n    Flight time            =      4.864 hr\n    Wing fuel volume       =     0.0551 m^3\n    Total fuel volume      =      0.117 m^3\n```\n:::\n:::\n\n\nThis is a thoroughly sensible airplane: a 887 kg, 13\\.1 m-span machine — Cessna-172 class — cruising at 57 m/s. Several features of the optimum are worth reading closely:\n\n* **The wing is sized by the landing requirement.** At 8705 N of lift at 25 m/s with $C_{L,\\max}$ flaps, the stall constraint is exactly active. Cruise then happens at a low $C_L$ of 0\\.29 — the wing is \"too big\" for cruise because the runway, not the cruise, set its size.\n* **The fuel splits between wing and fuselage.** Of the 117 L of fuel, 55 L rides in the wing (free bending relief, no drag) and 62 L in the fuselage. The optimizer stops adding fuselage volume exactly where the marginal drag cost of a fatter fuselage balances the marginal structural cost of carrying fuel in the wing... a trade you would not want to close by hand.\n* **The airplane does *not* fly at its best L/D.** Cruise L/D is 25\\.6, noticeably below the airframe's maximum. That is not a mistake, and the next figure shows why.\n\n::: {#cell-fig-simpleac-speed .cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\"}\nimport _common\nimport matplotlib.pyplot as plt\n\n# Freeze the optimized design (geometry, weights), then trim it across speeds:\nV_grid = np.linspace(35, 90, 500)                    # candidate cruise speeds [m/s]\nq = 0.5 * sol(rho) * V_grid**2                       # dynamic pressure [Pa]\nCL_trim = sol(W_0 + W_w + 0.5 * W_f) / (q * sol(S))  # C_L required for L = W\nRe_grid = sol(rho / mu) * V_grid * np.sqrt(sol(S / AR))\n\nD_fuse = q * sol(CDA0)\nD_prof = q * sol(S) * sol(k * S_wetratio) * 0.074 / Re_grid**0.2\nD_ind  = q * sol(S) * CL_trim**2 / (np.pi * sol(AR * e))\nD_trim = D_fuse + D_prof + D_ind\n\nfuel_per_km = sol(TSFC) * D_trim / V_grid * 1e3      # fuel weight per distance [N/km]\n\nV_star = sol(V)\nV_minD = V_grid[np.argmin(D_trim)]\n\nfig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7, 6.8), sharex=True)\n\nc = _common.SERIES\nax1.plot(V_grid, D_trim, color=c[0])\nax1.plot(V_grid, D_ind, color=_common.TEXT_SECONDARY, lw=1.2)\nax1.plot(V_grid, D_prof, color=_common.TEXT_SECONDARY, lw=1.2)\nax1.plot(V_grid, D_fuse, color=_common.TEXT_SECONDARY, lw=1.2)\n_common.label_line(ax1, V_grid[-1], D_trim[-1], \"total\", c[0], dx=1)\n_common.label_line(ax1, V_grid[0], D_ind[0], \"induced\", _common.TEXT_SECONDARY,\n                   dx=1, dy=25)\n_common.label_line(ax1, V_grid[-1], D_prof[-1], \"wing profile\", _common.TEXT_SECONDARY, dx=1)\n_common.label_line(ax1, V_grid[-1], D_fuse[-1], \"fuselage\", _common.TEXT_SECONDARY, dx=1)\nax1.set_ylabel(\"Drag [N]\")\nax1.set_title(\"Minimum drag is at low speed...\")\nax1.set_ylim(bottom=0)\n\nax2.plot(V_grid, fuel_per_km, color=c[0])\nax2.set_xlabel(\"Cruise speed [m/s]\")\nax2.set_ylabel(\"Fuel burned per distance [N/km]\")\nax2.set_title(\"...but minimum fuel-per-distance is what the mission rewards\")\nax2.set_ylim(bottom=0)\n\nfor ax in (ax1, ax2):\n    ax.axvline(V_minD, color=_common.TEXT_SECONDARY, lw=0.8, ls=\"--\", zorder=0)\n    ax.axvline(V_star, color=c[3], lw=0.8, ls=\"--\", zorder=0)\nax1.text(V_minD, ax1.get_ylim()[1] * 0.97, \" min drag\\n (best glide)\",\n         color=_common.TEXT_SECONDARY, va=\"top\", fontsize=8)\nax1.text(V_star, ax1.get_ylim()[1] * 0.97, \" chosen cruise\",\n         color=c[3], va=\"top\", fontsize=8)\n\nplt.subplots_adjust(right=0.85, hspace=0.35)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Trim drag of the optimized design, flown across cruise speeds at mid-cruise weight. Top: drag components. Bottom: what actually matters for fuel burn — drag divided by speed (fuel weight burned per unit distance). The optimizer cruises at the minimum of $D/V$, not the minimum of $D$: since flight *time* falls as speed rises, the best-range speed is faster than the best-glide speed.](10-aircraft-sizing-simpleac_files/figure-html/fig-simpleac-speed-output-1.png){#fig-simpleac-speed width=979 height=910}\n:::\n:::\n\n\nBecause total fuel equals (fuel per distance) × (range), the optimizer minimizes $D/V$, not $D$ — and the $D/V$ minimum sits at 57\\.2 m/s, essentially exactly the chosen cruise speed of 57\\.1 m/s. Induced drag falls with speed while profile drag rises; dividing by $V$ shifts the balance point toward higher speed. This is the classic result that best-range speed is faster than best-endurance/best-glide speed, discovered here by a nonlinear program rather than told to it.\n\n## Cross-check: geometric programming agrees {#sec-simpleac-gpkit}\n\nSimPleAC's authors solved this problem with GPKit, which transforms it into a (log-space convex) geometric program and returns a *certified globally optimal* solution. That printed solution gives us a rare thing in design optimization: ground truth to compare against.\n\n::: {#27e3e937 .cell execution_count=10}\n``` {.python .cell-code}\nfrom IPython.display import Markdown\n\n# GPKit's solution, transcribed from the original SimPleAC run\n# (github.com/convexengineering/gplibrary, SP/SimPleAC; printed to 3-4 sig. figs):\ncomparison = [\n    # quantity            unit    AeroSandbox value       GPKit value\n    (\"Aspect ratio\",      \"-\",    sol(AR),                12.1),\n    (\"Wing area\",         \"m^2\",  sol(S),                 14.15),\n    (\"Cruise speed\",      \"m/s\",  sol(V),                 57.11),\n    (\"Gross weight\",      \"N\",    sol(W),                 8705),\n    (\"Cruise C_L\",        \"-\",    sol(C_L),               0.2901),\n    (\"Fuel weight\",       \"N\",    sol(W_f),               937.8),\n    (\"Fuselage tank\",     \"m^3\",  sol(V_f_fuse),          0.0619),\n    (\"Wing tank\",         \"m^3\",  sol(V_f_wing),          0.0551),\n    (\"Drag\",              \"N\",    sol(D),                 321.3),\n    (\"Drag coefficient\",  \"-\",    sol(C_D),               0.01132),\n    (\"Skin friction\",     \"-\",    sol(C_f),               0.003491),\n    (\"Fuselage drag area\",\"m^2\",  sol(CDA0),              0.00619),\n    (\"Cruise L/D\",        \"-\",    sol(C_L / C_D),         25.63),\n    (\"Reynolds number\",   \"-\",    sol(Re),                4.279e6),\n    (\"Flight time\",       \"hr\",   sol(T_flight) / u.hour, 4.864),\n    (\"Fuel volume\",       \"m^3\",  sol(V_f),               0.117),\n    (\"Wing weight\",       \"N\",    sol(W_w),               1517),\n    (\"... structural\",    \"N\",    sol(W_w_strc),          667.8),\n    (\"... skin\",          \"N\",    sol(W_w_surf),          849.2),\n]\n\nMarkdown(\n    \"| Quantity | Unit | AeroSandbox | GPKit | Rel. difference |\\n\"\n    \"|:---|:---|---:|---:|---:|\\n\"\n    + \"\\n\".join(\n        f\"| {name} | {unit} | {asb_val:.6g} | {gp_val:.4g} | {asb_val / gp_val - 1:+.2e} |\"\n        for name, unit, asb_val, gp_val in comparison\n    )\n)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=10}\n| Quantity | Unit | AeroSandbox | GPKit | Rel. difference |\n|:---|:---|---:|---:|---:|\n| Aspect ratio | - | 12.1049 | 12.1 | +4.04e-04 |\n| Wing area | m^2 | 14.1542 | 14.15 | +2.95e-04 |\n| Cruise speed | m/s | 57.106 | 57.11 | -6.96e-05 |\n| Gross weight | N | 8704.82 | 8705 | -2.10e-05 |\n| Cruise C_L | - | 0.290128 | 0.2901 | +9.65e-05 |\n| Fuel weight | N | 937.756 | 937.8 | -4.70e-05 |\n| Fuselage tank | m^3 | 0.0619038 | 0.0619 | +6.13e-05 |\n| Wing tank | m^3 | 0.0550997 | 0.0551 | -5.93e-06 |\n| Drag | N | 321.309 | 321.3 | +2.82e-05 |\n| Drag coefficient | - | 0.0113188 | 0.01132 | -1.08e-04 |\n| Skin friction | - | 0.00349109 | 0.003491 | +2.70e-05 |\n| Fuselage drag area | m^2 | 0.00619038 | 0.00619 | +6.13e-05 |\n| Cruise L/D | - | 25.6325 | 25.63 | +9.57e-05 |\n| Reynolds number | - | 4.27908e+06 | 4.279e+06 | +1.92e-05 |\n| Flight time | hr | 4.86425 | 4.864 | +5.07e-05 |\n| Fuel volume | m^3 | 0.117003 | 0.117 | +2.97e-05 |\n| Wing weight | N | 1517.06 | 1517 | +4.05e-05 |\n| ... structural | N | 667.811 | 667.8 | +1.64e-05 |\n| ... skin | N | 849.25 | 849.2 | +5.94e-05 |\n:::\n:::\n\n\n\n\nEvery quantity matches to within GPKit's printed precision — the largest relative difference across all 19 quantities is 4\\.0e\\-04, which is rounding in GPKit's 3-to-4-significant-figure output, not real disagreement. Both solvers drive their own convergence tolerances far tighter than this. Since the GP solution is provably the global optimum of this problem, we've confirmed that the AD/IPOPT approach landed on the global optimum here too.\n\nIt's worth being precise about what each approach buys you, since \"GP vs. NLP\" is a recurring design decision in this field:\n\n* **Speed:** comparable, and both are effectively instant at this scale (milliseconds). The AD approach also solved a *smaller* problem here, since intermediate quantities didn't need to be decision variables.\n* **Guarantees:** GP certifies global optimality — *of a GP-compatible model*. If your true physics isn't GP-compatible (transonic drag rise, stall, tabulated engine decks, ...), you must either approximate it with GP-compatible surrogates — at which point the certificate applies to the approximation, not your problem — or abandon the guarantee via signomial programming. The AD approach never had the certificate, but it also never restricted what you're allowed to write: any differentiable model, including everything in the rest of this book, is fair game.\n* **Robustness:** GP needs no initial guess; the AD approach converges reliably given order-of-magnitude guesses (ours were off by up to 2× and it did not matter), but can fail if guesses are wildly wrong. Engineering intuition is usually more than sufficient.\n\nIn short: when a problem *is* GP-compatible, both methods find the same answer at the same speed; when it isn't, only one of them can express it. For a fuller treatment of solver behavior and failure modes, see [Solvers and Solutions](03-solvers-and-solutions.qmd).\n\n## Sensitivities for free {#sec-simpleac-sensitivities}\n\nHere's the question every design review actually asks: *\"What's that requirement costing us?\"* If the landing-speed requirement were relaxed by 5%, how much fuel would we save? What if the engine's TSFC improved by 10%? Is empty weight or drag the better place to spend engineering effort?\n\nThe remarkable fact is that the optimizer has already computed all of these answers. At a constrained optimum, each constraint carries a **Lagrange multiplier** (a *dual variable* or *shadow price*): the rate at which the optimal objective would improve if that constraint were relaxed. IPOPT computes these as part of solving the problem. Formally, if the problem is\n\n$$\nJ^*(p) = \\min_x \\; f(x, p) \\quad \\text{s.t.} \\quad g(x, p) \\leq 0,\n$$\n\nwith parameters $p$, then the envelope theorem (equivalently, first-order NLP sensitivity analysis) says\n\n$$\n\\frac{\\mathrm{d}J^*}{\\mathrm{d}p}\n= \\frac{\\partial f}{\\partial p} + \\lambda^\\top \\frac{\\partial g}{\\partial p}\n= \\frac{\\partial \\mathcal{L}}{\\partial p},\n$$\n\nevaluated at the optimum — the *total* derivative of the optimal cost, accounting for how the entire optimal design re-arranges itself, equals a *partial* derivative of the Lagrangian $\\mathcal{L} = f + \\lambda^\\top g$, which needs no re-solving at all. This is why we declared the constants as `opti.parameter()`s: AeroSandbox's `Opti` is a thin subclass of CasADi's, so we can drop one level down and evaluate this expression symbolically.\n\nOne more transformation makes the result maximally readable. Raw derivatives have awkward units ($\\mathrm{d}W_f / \\mathrm{d}\\,\\mathrm{TSFC}$ is in newton-seconds...). Instead we report **log-log sensitivities**,\n\n$$\n\\hat{S}_p \\;=\\; \\frac{\\mathrm{d}\\ln J^*}{\\mathrm{d}\\ln p} \\;=\\; \\frac{p}{J^*}\\frac{\\mathrm{d}J^*}{\\mathrm{d}p},\n$$\n\nread as \"*a 1% increase in $p$ produces an $\\hat{S}_p$% increase in optimal fuel burn*\" — dimensionless, comparable across parameters, and exactly the sensitivity format GPKit reports.\n\n::: {#b804e4f4 .cell execution_count=12}\n``` {.python .cell-code}\nimport casadi as cas\n\nconstants = {\n    \"g\": g, \"mu\": mu, \"rho\": rho, \"rho_f\": rho_f,\n    \"C_Lmax\": C_Lmax, \"e\": e, \"k\": k, \"N_ult\": N_ult,\n    \"S_wetratio\": S_wetratio, \"tau\": tau,\n    \"W_W_coeff1\": W_W_coeff1, \"W_W_coeff2\": W_W_coeff2,\n    \"Range\": Range, \"TSFC\": TSFC, \"V_min\": V_min, \"W_0\": W_0,\n}\n\nlagrangian = opti.f + cas.dot(opti.lam_g, opti.g)\n\nsens = {  # d(ln J*) / d(ln p) for each parameter p\n    name: float(sol(cas.gradient(lagrangian, p) * p / opti.f))\n    for name, p in constants.items()\n}\n\nfor name, s in sorted(sens.items(), key=lambda item: -abs(item[1])):\n    print(f\"{name:12s} {s:+7.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nV_min         -1.311\nRange         +1.199\nTSFC          +1.199\nW_0           +0.936\nS_wetratio    +0.898\nk             +0.898\nC_Lmax        -0.655\ne             -0.255\nmu            +0.180\nrho           -0.146\ntau           -0.140\nW_W_coeff2    +0.121\nN_ult         +0.095\nW_W_coeff1    +0.095\nrho_f         -0.091\ng             -0.091\n```\n:::\n:::\n\n\n::: {#cell-fig-simpleac-tornado .cell execution_count=13}\n``` {.python .cell-code code-fold=\"true\"}\nimport _common\nimport matplotlib.pyplot as plt\n\nnames, vals = zip(*sorted(sens.items(), key=lambda item: abs(item[1])))\ncolors = [_common.SERIES[3] if v > 0 else _common.SERIES[0] for v in vals]\n\nfig, ax = plt.subplots(figsize=(7, 5.2))\nax.barh(names, vals, color=colors, height=0.65)\nfor i, v in enumerate(vals):\n    ax.text(v + (0.03 if v > 0 else -0.03), i, f\"{v:+.2f}\",\n            va=\"center\", ha=\"left\" if v > 0 else \"right\",\n            fontsize=8, color=_common.TEXT_PRIMARY)\nax.set_xlabel(\"Fuel-burn sensitivity  d ln($W_f$) / d ln($p$)  [-]\")\nax.set_title(\"Where the fuel burn comes from\")\nax.set_xlim(-1.75, 1.75)\nax.axvline(0, color=_common.TEXT_SECONDARY, lw=0.8)\nax.text(1.7, len(vals) - 0.5, \"more fuel →\", color=_common.SERIES[3],\n        ha=\"right\", fontsize=8, fontweight=\"bold\")\nax.text(-1.7, len(vals) - 0.5, \"← less fuel\", color=_common.SERIES[0],\n        ha=\"left\", fontsize=8, fontweight=\"bold\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Log-log sensitivities of optimal fuel burn to every model input: the percent change in fuel burn per percent increase in each parameter. Computed from the duals of a single solve — no re-solving, no finite differencing.](10-aircraft-sizing-simpleac_files/figure-html/fig-simpleac-tornado-output-1.png){#fig-simpleac-tornado width=985 height=728}\n:::\n:::\n\n\nThis chart repays close reading — it is, in effect, an audit of the whole design problem:\n\n* **The landing-speed requirement is the most expensive line in the spec.** $\\hat{S}_{V_\\min} =$ \\-1\\.31: every 1% of allowed landing speed buys 1\\.31% of fuel, because it shrinks the wing that the runway — not the cruise — is sizing. If a design review is looking for requirements to challenge, the duals point straight at this one. Relatedly, better flaps ($C_{L,\\max}$, \\-0\\.66) buy fuel for exactly the same reason.\n* **Range and TSFC compound beyond 1:1.** Both sit at \\+1\\.20: a 1% longer mission costs 1\\.20% more fuel, because extra fuel adds weight, which adds structure and drag, which adds fuel — the Breguet spiral, priced exactly.\n* **Empty weight passes through at almost exactly 1:1** ($\\hat{S}_{W_0} =$ \\+0\\.94), and profile drag ($k$, $S_\\mathrm{wet}/S$) at \\+0\\.90 — a useful exchange rate between the structures group and the aero group.\n* **Parameters that only ever appear multiplied together have identical sensitivities** — compare `Range` & `TSFC`, `k` & `S_wetratio`, `N_ult` & `W_W_coeff1`, `g` & `rho_f`. The duals are rediscovering the model's nondimensional structure: only the products matter, so their log-sensitivities must match.\n* **Sensitivities audit your assumptions.** Gravity has a *negative* sensitivity (\\-0\\.09) — stronger gravity means *less* fuel?! It's correct, given what the model holds fixed: $W_0$ is specified as a *weight*, so heavier gravity doesn't make the airplane heavier; the only surviving effect is that the same fuel *weight* occupies less volume ($V_f = W_f / \\rho_f g$), shrinking the draggy fuselage tank. A surprising sign in a sensitivity table is usually the model telling you precisely which assumption you forgot you made.\n\nAs a check that these dual-based numbers mean what we claim, compare against a brute-force finite difference — re-solve the whole problem with the range requirement stretched 2% and measure the fuel change:\n\n::: {#cd38ff23 .cell execution_count=14}\n``` {.python .cell-code}\nR_0 = sol(Range)\n\nsol_perturbed = opti.solve(\n    parameter_mapping={Range: 1.02 * R_0},  # re-solve at 102% range\n    verbose=False,\n)\n\nsens_fd = np.log(sol_perturbed(W_f) / sol(W_f)) / np.log(1.02)\n\nprint(f\"d(ln W_f)/d(ln Range),  from duals            : {sens['Range']:.4f}\")\nprint(f\"d(ln W_f)/d(ln Range),  finite difference (+2%): {sens_fd:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nd(ln W_f)/d(ln Range),  from duals            : 1.1989\nd(ln W_f)/d(ln Range),  finite difference (+2%): 1.2012\n```\n:::\n:::\n\n\nThey agree to 0\\.2% (the small residual is real curvature across the 2% step, not error). The difference in cost is the point: the finite difference needed a full re-solve *per parameter, per direction*; the duals priced all 16 parameters simultaneously, using only information the original solve already had.\n\n## From local sensitivities to design sweeps {#sec-simpleac-sweeps}\n\nDuals give the *slope* of the optimal-cost curve at one point. To see the whole curve — \"what does the 2,500 km version of this airplane look like?\" — we re-solve across a parameter range. Because each re-solve starts from a compiled problem, this is cheap; the craft is in making it *reliable*. Two practices help (both discussed further in [Solvers and Solutions](03-solvers-and-solutions.qmd)):\n\n1. **Sweep by continuation**: walk outward from the solved nominal point, warm-starting each solve from its neighbor's solution via `opti.set_initial_from_sol()`, so the solver always starts near an optimum.\n2. **Warm-start the primal variables only** (`initialize_duals=False`): re-using converged duals from a *different* parameter value tends to hurt interior-point methods more than it helps.\n\n::: {#8f485f4a .cell execution_count=15}\n``` {.python .cell-code}\nranges = np.linspace(250e3, 3000e3, 30)  # mission ranges to study [m]\n\nsweep = {}\nfor direction in [+1, -1]:  # walk up from the nominal range, then down\n    last_sol = sol\n    to_solve = ranges[ranges > R_0] if direction > 0 else ranges[ranges <= R_0][::-1]\n    for R in to_solve:\n        opti.set_initial_from_sol(last_sol, initialize_duals=False)\n        last_sol = opti.solve(parameter_mapping={Range: R}, verbose=False)\n        sweep[R] = last_sol\n\nprint(f\"Re-designed the airplane for {len(sweep)} different missions.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRe-designed the airplane for 30 different missions.\n```\n:::\n:::\n\n\nAll 30 solves converge — a 12× spread in mission range, each point a *fully re-optimized airplane*. (For one-liner sweeps, `opti.solve_sweep()` packages this pattern; the explicit loop shown here gives you control over ordering and warm starts when a problem needs coaxing.)\n\n::: {#cell-fig-simpleac-sweep .cell execution_count=16}\n``` {.python .cell-code code-fold=\"true\"}\nimport _common\nimport matplotlib.pyplot as plt\n\nRs = np.array(sorted(sweep.keys()))\nget = lambda x: np.array([sweep[R](x) for R in Rs])\nWf_sweep = get(W_f)\n\nRs_km = Rs / 1e3\nR_0_km = R_0 / 1e3\nWf_pred = sol(W_f) * (Rs / R_0) ** sens[\"Range\"]  # dual-implied power law\n\nc = _common.SERIES\nfig, (ax1, ax2) = plt.subplots(2, 1, figsize=(7, 6.8), sharex=True)\n\nax1.plot(Rs_km, Wf_sweep, color=c[0])\nax1.plot(Rs_km, Wf_pred, color=c[2], ls=\"--\", lw=1.5)\nax1.plot(R_0_km, sol(W_f), \"o\", color=c[3], ms=6, zorder=5)\nax1.annotate(\"nominal design\\n(1,000 km)\", xy=(R_0_km, sol(W_f)),\n             xytext=(R_0_km + 60, sol(W_f) + 900), color=c[3], fontsize=8)\n_common.label_line(ax1, Rs_km[-1], Wf_sweep[-1], \"re-optimized\\nat each range\", c[0], dx=25)\n_common.label_line(\n    ax1, Rs_km[-1], Wf_pred[-1],\n    f\"dual extrapolation:\\n$W_f \\\\propto R^{{{sens['Range']:.2f}}}$\", c[2], dx=25,\n)\nax1.set_ylabel(\"Fuel weight [N]\")\nax1.set_title(\"The dual predicts the trend; re-solving gives the truth\")\nax1.set_ylim(bottom=0)\n\nfor y, color, ls, name, dy in [\n    (get(W) / sol(W), c[4], \"-\", \"gross weight\", -0.04),\n    (get(S) / sol(S), c[1], \"--\", \"wing area\", +0.03),\n    (get(AR) / sol(AR), _common.TEXT_SECONDARY, \"-\", \"aspect ratio\", 0),\n    (get(V) / sol(V), c[3], \"-\", \"cruise speed\", 0),\n]:\n    ax2.plot(Rs_km, y, color=color, ls=ls)\n    _common.label_line(ax2, Rs_km[-1], y[-1], name, color, dx=25, dy=dy)\nax2.axhline(1, color=_common.GRID, lw=0.8)\n\n# Mark where the fuel-volume constraint becomes active:\nvol_slack = get(V_f_wing + V_f_fuse - V_f)\nkink_R_km = Rs_km[np.argmax(vol_slack < 1e-6)]\nax2.axvline(kink_R_km, color=_common.TEXT_SECONDARY, lw=0.8, ls=\":\", zorder=0)\nax2.text(kink_R_km + 30, 1.42, \"fuselage tank\\nneeded →\",\n         color=_common.TEXT_SECONDARY, fontsize=8)\n\nax2.set_xlabel(\"Mission range [km]\")\nax2.set_ylabel(\"Relative to nominal design [-]\")\nax2.set_title(\"Every point is a different airplane\")\n\nplt.subplots_adjust(right=0.82, hspace=0.3)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Sweeping the range requirement from 250 km to 3,000 km. Top: optimal fuel burn, with the power-law extrapolation implied by the nominal design's dual (dashed). Bottom: how the re-optimized design itself morphs — longer-range airplanes are bigger, heavier, and slower. The wing-area curve (dashed) lies exactly on top of gross weight, because the landing constraint pins the wing loading at every range.](10-aircraft-sizing-simpleac_files/figure-html/fig-simpleac-sweep-output-1.png){#fig-simpleac-sweep width=1032 height=910}\n:::\n:::\n\n\n::: {#d9bf25a4 .cell execution_count=17}\n``` {.python .cell-code}\nlocal_exponent = np.log(Wf_sweep[-1] / Wf_sweep[-2]) / np.log(Rs[-1] / Rs[-2])\nextrap_error = Wf_pred[-1] / Wf_sweep[-1] - 1\n```\n:::\n\n\nThe two views are complementary. Near the nominal point, the dual-implied power law — $W_f \\propto R^{\\hat{S}}$ with $\\hat{S} =$ 1\\.20 — tracks the true re-optimized curve closely — the dual really is the local exponent of the design's cost growth. Far from it, the extrapolation drifts: by 3,000 km it underpredicts fuel burn by 23%, because the exponent itself grows along the sweep (the local slope between the last two sweep points is already 1\\.85) as the Breguet weight spiral compounds. Meanwhile, the bottom panel shows the *design* responding: the 3,000 km airplane carries 4\\.8× the fuel of the nominal one with 1\\.5× the wing area, and cruises about 11% slower — while the optimal aspect ratio barely moves. Duals for local exchange rates, sweeps for global trades: use both.\n\nThe bottom panel also holds two structural lessons about reading sweeps of *optima*:\n\n* **The wing-area curve (dashed) lies exactly on top of the gross-weight curve.** That's not coincidence: the landing constraint stays binding at every single range, pinning the wing loading of all 30 airplanes at $W/S = \\tfrac{1}{2}\\rho \\, C_{L,\\max} V_\\min^2 =$ 615 Pa. The runway sizes the wing for the 250 km airplane exactly as it does for the 3,000 km one, so wing area simply *is* gross weight in disguise.\n* **The kink near 534 km marks a constraint-activity change.** Below it, the mission's fuel fits entirely inside the wing box: the optimizer shrinks the fuselage tank — and with it, this model's fuselage drag — essentially to zero. Above it, fuel spills into the fuselage, and every additional kilometer of range now buys drag as well as weight. Sweeps of optimal designs are typically piecewise-smooth, and each kink flags a qualitative change in *what is limiting the design* — they're worth hunting down and explaining, every time.\n\n## Where to go next {#sec-simpleac-next}\n\nThis chapter completes the core design-optimization pattern of this book: write physics as constraints, let the optimizer close the loops, then interrogate the optimum (duals, sweeps) rather than just admiring it. From here:\n\n* [Solvers and Solutions](03-solvers-and-solutions.qmd) goes deeper on the machinery used here — parameters and duals, warm starts, sweep tooling, and what to do when a solve fails.\n* The complete design studies scale this same pattern up: an [aerostructural wing](13-aerostructural-wing.qmd) where the \"wing weight model\" becomes an actual coupled beam + VLM analysis, and a [transport aircraft](14-transport-aircraft-design.qmd) where the weight buildup grows to ~25 components with real engine and aero models.\n* If the wing-weight or drag models here felt too coarse, [Structures](08-structures.qmd) and [Aircraft Aerodynamics](06-aircraft-aerodynamics.qmd) show the higher-fidelity, still-differentiable models that can drop into exactly this formulation.\n\n",
    "supporting": [
      "10-aircraft-sizing-simpleac_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}