{
  "hash": "f51c6ba16599a20d15bb88b16750c227",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nexecute:\n  warning: false\n---\n\n# Aircraft Aerodynamics {#sec-aircraft-aerodynamics}\n\n\n\nYou have an airplane geometry. Now you need forces and moments: how much lift at this angle of attack, how much drag at that cruise condition, whether the airplane is stable, and how all of that changes as the optimizer morphs the design. This chapter covers AeroSandbox's built-in 3D aerodynamics analyses — what each one models, what each one costs, and how much to trust them. You will learn to run the same airplane through four solvers of increasing fidelity, extract stability derivatives, do a first aerodynamic shape optimization, and finally check all four methods against wind-tunnel data on a swept flying wing.\n\nEvery analysis here shares one interface: construct it from an `asb.Airplane` (@sec-geometry) and an `asb.OperatingPoint`, call `.run()`, and get back a dictionary of forces, moments, and nondimensional coefficients with identical keys. Because the methods are interchangeable, you can prototype a design study with the fastest one and swap in a higher-fidelity one with a two-line change. And because every method is written in `aerosandbox.numpy`, each one is automatically differentiable — any of them can sit inside an `asb.Opti` problem as a design constraint.\n\n## The fidelity ladder {#sec-aircraft-aero-ladder}\n\nThere is no single \"best\" aerodynamics model — only the right tool for the current design question. AeroSandbox gives you a ladder:\n\n| Method | Class | Physics | Viscous? | Valid envelope | Relative cost |\n|---|---|---|---|---|---|\n| Component buildup | `asb.AeroBuildup` | DATCOM-style analytic + empirical buildup, incl. fuselages | Yes | Any $\\alpha, \\beta$ (±180°), subsonic through supersonic (reduced accuracy transonic) | Fastest; vectorizes over operating points |\n| Vortex lattice | `asb.VortexLatticeMethod` | 3D lifting-surface potential flow | No | Attached flow, small-ish angles | Fast; scales with panel count |\n| Lifting line | `asb.LiftingLine` | Spanwise horseshoe-vortex system + NeuralFoil 2D viscous data | Yes | Attached flow, moderate angles | Fast |\n| Nonlinear lifting line | `asb.NonlinearLiftingLine` | Same, but circulation solved consistently with *nonlinear* 2D polars (implicit solve) | Yes | Attached flow, into early stall | Slowest (iterative solve) |\n\n: The 3D aerodynamics methods in AeroSandbox, ordered roughly by cost. {#tbl-aero-ladder}\n\nA good default workflow: use `AeroBuildup` for design-space exploration and full-envelope work (it is the only method here that models fuselage aerodynamics and remains well-behaved at extreme attitudes), then spot-check the converged design with the vortex lattice or lifting-line methods — or with external codes like AVL and XFoil (@sec-external-tools).\n\n## The running example {#sec-aircraft-aero-testcase}\n\nConcrete first: we need an airplane. Here is a small RC-glider-class aircraft — a main wing, tail surfaces (with an elevator on the horizontal stabilizer), and a streamlined fuselage. The geometry classes themselves are covered in @sec-geometry; skim the code and note only that distances are in meters and angles in degrees.\n\n::: {#8e8d3524 .cell execution_count=2}\n``` {.python .cell-code}\nimport aerosandbox as asb\nimport aerosandbox.numpy as np\n\nwing_airfoil = asb.Airfoil(\"sd7037\")\ntail_airfoil = asb.Airfoil(\"naca0010\")\n\nairplane = asb.Airplane(\n    name=\"Peter's Glider\",\n    xyz_ref=[0, 0, 0],  # CG location; also the moment reference point\n    wings=[\n        asb.Wing(\n            name=\"Main Wing\",\n            symmetric=True,\n            xsecs=[\n                asb.WingXSec(  # Root\n                    xyz_le=[0, 0, 0],\n                    chord=0.18,\n                    twist=2,  # deg\n                    airfoil=wing_airfoil,\n                ),\n                asb.WingXSec(  # Mid\n                    xyz_le=[0.01, 0.5, 0],\n                    chord=0.16,\n                    twist=0,\n                    airfoil=wing_airfoil,\n                ),\n                asb.WingXSec(  # Tip\n                    xyz_le=[0.08, 1, 0.1],\n                    chord=0.08,\n                    twist=-2,\n                    airfoil=wing_airfoil,\n                ),\n            ],\n        ),\n        asb.Wing(\n            name=\"Horizontal Stabilizer\",\n            symmetric=True,\n            xsecs=[\n                asb.WingXSec(  # Root\n                    xyz_le=[0, 0, 0],\n                    chord=0.1,\n                    twist=-10,\n                    airfoil=tail_airfoil,\n                    control_surfaces=[\n                        asb.ControlSurface(\n                            name=\"Elevator\",\n                            symmetric=True,  # Deflects together on both sides\n                            hinge_point=0.75,  # Hinge at 75% chord\n                        )\n                    ],\n                ),\n                asb.WingXSec(  # Tip\n                    xyz_le=[0.02, 0.17, 0],\n                    chord=0.08,\n                    twist=-10,\n                    airfoil=tail_airfoil,\n                ),\n            ],\n        ).translate([0.6, 0, 0.06]),\n        asb.Wing(\n            name=\"Vertical Stabilizer\",\n            symmetric=False,\n            xsecs=[\n                asb.WingXSec(\n                    xyz_le=[0, 0, 0],\n                    chord=0.1,\n                    airfoil=tail_airfoil,\n                ),\n                asb.WingXSec(\n                    xyz_le=[0.04, 0, 0.15],\n                    chord=0.06,\n                    airfoil=tail_airfoil,\n                ),\n            ],\n        ).translate([0.6, 0, 0.07]),\n    ],\n    fuselages=[\n        asb.Fuselage(\n            name=\"Fuselage\",\n            xsecs=[\n                asb.FuselageXSec(\n                    xyz_c=[0.8 * xi - 0.1, 0, 0.1 * xi - 0.03],\n                    radius=0.6 * asb.Airfoil(\"dae51\").local_thickness(x_over_c=xi),\n                )\n                for xi in np.cosspace(0, 1, 30)\n            ],\n        )\n    ],\n)\n```\n:::\n\n\n::: {#fig-glider-three-view .cell execution_count=3}\n``` {.python .cell-code}\nairplane.draw_three_view()\n```\n\n::: {.cell-output .cell-output-display}\n![Three-view (plus isometric) of the example glider, drawn with `airplane.draw_three_view()`.](06-aircraft-aerodynamics_files/figure-html/fig-glider-three-view-output-1.png){#fig-glider-three-view-1 width=1896 height=1896}\n:::\n\n::: {#fig-glider-three-view-2 .cell-output .cell-output-display execution_count=3}\n```\narray([[<Axes3D: zlabel='$z_g$ [m]'>, <Axes3D: >],\n       [<Axes3D: xlabel='$x_g$ [m]', ylabel='$y_g$ [m]'>, <Axes3D: >]],\n      dtype=object)\n```\n:::\n:::\n\n\n::: {#097fd010 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\n<module '_common' from '/tmp/claude-1000/-home-psharpe-gh-AeroSandbox/1ccf6b40-3256-4f8d-9484-ebe00c7e55db/scratchpad/book-staging/_common.py'>\n```\n:::\n:::\n\n\n## AeroBuildup: the workhorse {#sec-aircraft-aero-aerobuildup}\n\n`asb.AeroBuildup` computes forces and moments the way a classical conceptual-design workbook does: component by component, combining analytic theory (lifting-surface slopes, slender-body theory) with empirical corrections for viscous and compressible effects. Its formulation is heavily inspired by the [USAF Digital DATCOM](https://en.wikipedia.org/wiki/United_States_Air_Force_Stability_and_Control_Digital_DATCOM), and many submodels are shared with it. Two properties make it the workhorse of this chapter:\n\n1. **It works everywhere.** It returns finite, smoothly-varying answers across all 360° of angle of attack and sideslip, at arbitrary angular rates, from low subsonic through supersonic. (Accuracy degrades far from normal flight — an answer at $\\alpha = 90°$ is order-of-magnitude correct, not precise — but it never explodes, which is exactly what an optimizer crawling through bad intermediate designs needs.)\n2. **It is fast and vectorized.** Analyzing thousands of operating points in a single call costs milliseconds per point, as we will measure below.\n\n### A single operating point\n\nAn analysis takes the airplane plus an `asb.OperatingPoint` describing the flight condition — velocity, altitude (via an `asb.Atmosphere`), $\\alpha$, $\\beta$, and body rates $p, q, r$:\n\n::: {#f0ba7499 .cell execution_count=5}\n``` {.python .cell-code}\nop_point = asb.OperatingPoint(\n    velocity=10,  # m/s\n    alpha=5,  # deg\n)\n\naero = asb.AeroBuildup(\n    airplane=airplane,\n    op_point=op_point,\n).run()\n\n\ndef scalar(x):\n    \"\"\"Collapse a size-1 array to a plain float, for printing.\"\"\"\n    return float(np.ravel(x)[0])\n\n\nfor key in [\"L\", \"D\", \"CL\", \"CD\", \"Cm\"]:\n    print(f\"{key:>2} = {scalar(aero[key]):8.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n L =  14.1459\n D =   0.7256\nCL =   0.7899\nCD =   0.0405\nCm =  -0.2177\n```\n:::\n:::\n\n\nAt 10 m/s and $\\alpha = 5°$, the glider makes 14\\.1 N of lift against 0\\.73 N of drag — a lift-to-drag ratio of 19\\.5.\n\nThe returned dictionary contains much more than these five entries. Forces `F` and moments `M` come as $[x, y, z]$ vectors in three frames, distinguished by suffix:\n\n| Frame | Keys | Orientation |\n|---|---|---|\n| Geometry | `F_g`, `M_g` | $+x$ aft, $+y$ out the right wing, $+z$ up — same frame the geometry is defined in |\n| Body | `F_b`, `M_b` | $+x$ out the nose, $+y$ out the right wing, $+z$ down |\n| Wind | `F_w`, `M_w` | $+x$ along the flight velocity (into the relative wind), $+z$ down |\n\n: Axes conventions for force and moment outputs. {#tbl-axes}\n\nThe scalar entries are breakouts of these vectors: lift `L`, drag `D`, and sideforce `Y` (wind axes, with $L = -F_{w,z}$ and $D = -F_{w,x}$); rolling/pitching/yawing moments `l_b`, `m_b`, `n_b` (body axes); and their nondimensional counterparts `CL`, `CD`, `CY`, `Cl`, `Cm`, `Cn`. Coefficients are normalized by `airplane.s_ref`, `c_ref`, and `b_ref`, which you can set explicitly or let AeroSandbox derive from the first wing. Moments are taken about `xyz_ref` — by default the airplane's `xyz_ref`, so make sure that point is where you think your CG is.\n\n### Polars: vectorizing over operating points\n\n`AeroBuildup` accepts array-valued operating points, so sweeping $\\alpha$ is one call, not a loop. Let's measure how fast:\n\n::: {#6b496767 .cell execution_count=6}\n``` {.python .cell-code}\nimport time\n\nalpha = np.linspace(-15, 15, 300)\n\nt_start = time.time()\naero = asb.AeroBuildup(\n    airplane=airplane,\n    op_point=asb.OperatingPoint(velocity=10, alpha=alpha),\n).run()\nt_sweep = time.time() - t_start\n\nprint(f\"{len(alpha)} operating points analyzed in {t_sweep * 1e3:.0f} ms \"\n      f\"({t_sweep / len(alpha) * 1e3:.1f} ms per point)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n300 operating points analyzed in 565 ms (1.9 ms per point)\n```\n:::\n:::\n\n\nThat speed — about 2 ms per operating point for a complete airplane, viscous drag and all, with the per-point cost falling further for larger batches — is what makes AeroBuildup usable inside optimization loops and mission simulations. The resulting polars:\n\n::: {#cell-fig-aerobuildup-polars .cell execution_count=7}\n``` {.python .cell-code}\nimport _common  # book-wide plot style\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(4, 1, figsize=(7, 9.5), sharex=True)\n\nax[0].plot(alpha, aero[\"CL\"], color=_common.SERIES[0])\nax[0].set_ylabel(\"$C_L$ [-]\")\nax[0].set_title(\"Lift grows linearly, then softens toward stall\")\n\nax[1].plot(alpha, aero[\"CD\"], color=_common.SERIES[0])\nax[1].set_ylabel(\"$C_D$ [-]\")\nax[1].set_ylim(bottom=0)\nax[1].set_title(\"Drag: friction floor plus induced-drag parabola\")\n\nax[2].plot(alpha, aero[\"Cm\"], color=_common.SERIES[0])\nax[2].axhline(0, color=_common.TEXT_SECONDARY, linewidth=0.8, linestyle=\"--\")\nax[2].set_ylabel(\"$C_m$ [-]\")\nax[2].set_title(\"Pitching moment: negative slope = statically stable\")\n\nax[3].plot(alpha, aero[\"CL\"] / aero[\"CD\"], color=_common.SERIES[0])\nax[3].set_ylabel(\"$C_L/C_D$ [-]\")\nax[3].set_xlabel(r\"Angle of attack $\\alpha$ [deg]\")\nax[3].set_title(\"Aerodynamic efficiency peaks at a moderate angle of attack\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Whole-airplane polars from a single vectorized `AeroBuildup` call: lift, drag, pitching moment, and aerodynamic efficiency versus angle of attack.](06-aircraft-aerodynamics_files/figure-html/fig-aerobuildup-polars-output-1.png){#fig-aerobuildup-polars width=1034 height=1408}\n:::\n:::\n\n\n\n\nReading @fig-aerobuildup-polars like an aerodynamicist: the lift curve is linear in the attached-flow regime with softening at the extremes; drag has a friction-dominated bucket near zero lift and grows quadratically with lift (induced drag); the pitching-moment slope is negative, so the airplane is statically stable in pitch; and efficiency peaks at $L/D$ = 19\\.5 around $\\alpha$ = 4\\.6°.\n\n### The full envelope: any $\\alpha$, any $\\beta$\n\nMost aerodynamics tools quietly assume small angles. `AeroBuildup` does not — you can ask for the whole $(\\alpha, \\beta)$ envelope, which matters for spin analysis, high-angle trajectory simulation (e.g., rocket or re-entry-vehicle work), and making sure an optimizer can recover from absurd intermediate iterates. Here is the glider's lift coefficient over ±90° in both angles — about 3,700 operating points, again in one vectorized call:\n\n::: {#cell-fig-aerobuildup-envelope .cell execution_count=9}\n``` {.python .cell-code}\nimport _common\nimport matplotlib.pyplot as plt\nfrom matplotlib.patches import Rectangle\n\nBeta, Alpha = np.meshgrid(np.linspace(-90, 90, 61), np.linspace(-90, 90, 61))\n\naero_grid = asb.AeroBuildup(\n    airplane=airplane,\n    op_point=asb.OperatingPoint(\n        velocity=10,\n        alpha=Alpha.flatten(),\n        beta=Beta.flatten(),\n    ),\n).run()\n\nCL_grid = aero_grid[\"CL\"].reshape(Alpha.shape)\n\nfig, ax = plt.subplots(figsize=(7, 5.8))\nvmax = np.max(np.abs(CL_grid))\ncf = ax.contourf(Beta, Alpha, CL_grid, levels=21, cmap=\"RdBu_r\",\n                 vmin=-vmax, vmax=vmax, alpha=0.85)\ncs = ax.contour(Beta, Alpha, CL_grid, levels=11, colors=\"white\", linewidths=0.7)\nax.clabel(cs, fontsize=7, fmt=\"%.1f\")\nfig.colorbar(cf, label=\"Lift coefficient $C_L$ [-]\")\n\nax.add_patch(Rectangle((-10, -15), 20, 30, fill=False,\n                       edgecolor=_common.TEXT_PRIMARY, linewidth=1.2))\nax.annotate(\"conventional-analysis\\nenvelope\", xy=(12, -14),\n            fontsize=8, color=_common.TEXT_PRIMARY, va=\"top\")\n\nax.set_xlabel(r\"Sideslip angle $\\beta$ [deg]\")\nax.set_ylabel(r\"Angle of attack $\\alpha$ [deg]\")\nax.set_aspect(\"equal\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Lift coefficient across the full attitude envelope. The gray box marks the ±15° α, ±10° β region where conventional attached-flow analyses live; AeroBuildup returns smooth, plausible values far beyond it.](06-aircraft-aerodynamics_files/figure-html/fig-aerobuildup-envelope-output-1.png){#fig-aerobuildup-envelope width=961 height=764}\n:::\n:::\n\n\n### Control surfaces and trim\n\n`AeroBuildup` also models control-surface deflections. We declared an `asb.ControlSurface` named `\"Elevator\"` on the horizontal stabilizer back in @sec-aircraft-aero-testcase; `airplane.with_control_deflections()` returns a copy of the airplane with a deflection applied (positive = trailing edge down, by convention). Sweeping the elevator shifts the pitching-moment curve, which moves the trim point — the angle of attack where $C_m = 0$ and the airplane is in pitch equilibrium:\n\n::: {#cell-fig-trim .cell execution_count=10}\n``` {.python .cell-code}\nimport _common\nimport matplotlib.pyplot as plt\n\nalpha_trim_sweep = np.linspace(-8, 12, 60)\ndeflections = [-6, -3, 0, 3, 6]  # deg\nalpha_trims = []\n\nfig, ax = plt.subplots(figsize=(7, 4.5))\nfor i, deflection in enumerate(deflections):\n    aero_defl = asb.AeroBuildup(\n        airplane=airplane.with_control_deflections({\"Elevator\": deflection}),\n        op_point=asb.OperatingPoint(velocity=10, alpha=alpha_trim_sweep),\n    ).run()\n\n    # Trim: interpolate for the alpha where Cm crosses zero.\n    # (Cm decreases with alpha, so flip the arrays for np.interp.)\n    alpha_trim = np.interp(0, aero_defl[\"Cm\"][::-1], alpha_trim_sweep[::-1])\n    alpha_trims.append(alpha_trim)\n\n    color = _common.SERIES[i]\n    ax.plot(alpha_trim_sweep, aero_defl[\"Cm\"], color=color)\n    ax.plot(alpha_trim, 0, \"o\", color=color, markersize=6, zorder=4)\n    _common.label_line(\n        ax, alpha_trim_sweep[-1], aero_defl[\"Cm\"][-1],\n        rf\"$\\delta_e = {deflection:+d}°$\", color, dx=0.3,\n    )\n\nax.axhline(0, color=_common.TEXT_SECONDARY, linewidth=0.8, linestyle=\"--\")\nax.set_xlabel(r\"Angle of attack $\\alpha$ [deg]\")\nax.set_ylabel(\"Pitching moment coefficient $C_m$ [-]\")\nax.set_xlim(right=17)  # room for the direct labels\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Pitching-moment curves for several elevator deflections. Each dot marks the trim point (where the moment about the CG vanishes); up-elevator (negative deflection) trims the glider to a higher angle of attack.](06-aircraft-aerodynamics_files/figure-html/fig-trim-output-1.png){#fig-trim width=951 height=623}\n:::\n:::\n\n\n\n\nEach degree of down-elevator retrims the glider about 0\\.28° lower in angle of attack over this range — the kind of control-authority number you need when sizing tail surfaces.\n\n## Stability derivatives {#sec-aircraft-aero-stability}\n\nStatic stability analysis needs the *derivatives* of forces and moments with respect to flight condition — quantities like $C_{m_\\alpha}$ (pitch stiffness) and $C_{n_\\beta}$ (weathercock stability). Because every AeroSandbox model is automatically differentiable, you don't need finite-difference sweeps: `run_with_stability_derivatives()` returns exact derivatives alongside the baseline results. (This method exists on `AeroBuildup`, `VortexLatticeMethod`, and `LiftingLine` alike.)\n\n::: {#5c56ced9 .cell execution_count=12}\n``` {.python .cell-code}\nderivs = asb.AeroBuildup(\n    airplane=airplane,\n    op_point=asb.OperatingPoint(velocity=10, alpha=5),\n).run_with_stability_derivatives()  # computes d/d{alpha, beta, p, q, r}\n\nfor key in [\"CLa\", \"Cma\", \"Cmq\", \"Clb\", \"Clp\", \"Cnb\", \"Cnr\", \"x_np\"]:\n    print(f\"{key:>4} = {scalar(derivs[key]):+8.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n CLa =  +5.5248\n Cma =  -3.6760\n Cmq = -19.0596\n Clb =  -0.1701\n Clp =  -0.7000\n Cnb =  -0.0246\n Cnr =  -0.0158\nx_np =  +0.1005\n```\n:::\n:::\n\n\nThe key entries, and how to read their signs:\n\n| Derivative | Value | Meaning | Stable sign |\n|---|---|---|---|\n| $C_{L_\\alpha}$ | \\+5\\.52 /rad | Lift-curve slope | — |\n| $C_{m_\\alpha}$ | \\-3\\.68 /rad | Pitch stiffness | negative |\n| $C_{m_q}$ | \\-19\\.06 /rad | Pitch damping | negative |\n| $C_{l_\\beta}$ | \\-0\\.170 /rad | Dihedral effect (roll due to sideslip) | negative |\n| $C_{l_p}$ | \\-0\\.70 /rad | Roll damping | negative |\n| $C_{n_\\beta}$ | \\-0\\.025 /rad | Weathercock (yaw) stability | positive |\n| $C_{n_r}$ | \\-0\\.016 /rad | Yaw damping | negative |\n\n: Stability derivatives for the glider at $\\alpha = 5°$, from `AeroBuildup`. {#tbl-stability-derivs}\n\n\n\nLongitudinally, the report card is good: $C_{m_\\alpha}$ is strongly negative, and the neutral point sits at $x_{np}$ = 101 mm — behind the CG at $x = 0$, for a static margin of 67% of the reference chord. Directionally, though, AeroBuildup flags a problem: $C_{n_\\beta}$ = \\-0\\.025 /rad is slightly *negative*, meaning the destabilizing fuselage side-force slightly overpowers the small vertical tail. This is exactly the kind of cheap, early red flag you want from a conceptual-stage model: enlarging the vertical tail is free at the concept stage, and expensive after the airplane is built.\n\n::: {.callout-tip}\n## Derivatives of derivatives\n\nSince `run_with_stability_derivatives()` is itself built from differentiable operations, its outputs are differentiable too. You can put a constraint like `derivs[\"Cma\"] < -0.5` — or a static-margin band — directly into an `asb.Opti` problem, and the optimizer will reshape the airplane to satisfy it.\n:::\n\n## Vortex lattice method {#sec-aircraft-aero-vlm}\n\nOne rung up the ladder, `asb.VortexLatticeMethod` (VLM) solves an actual 3D flow problem: it meshes the lifting surfaces into panels of horseshoe vortices, enforces flow tangency at collocation points, and solves the resulting linear system. Unlike AeroBuildup's empirical buildup, the VLM *derives* the lift distribution, induced drag, and surface interference from potential-flow physics — so it captures planform effects (sweep, taper, twist, multi-surface interaction) with much higher fidelity. The price: it models inviscid, attached flow only. There is no friction or separation drag in a VLM answer, and fuselages are ignored.\n\nThe interface is identical:\n\n::: {#36cd2651 .cell execution_count=14}\n``` {.python .cell-code}\nvlm = asb.VortexLatticeMethod(\n    airplane=airplane,\n    op_point=asb.OperatingPoint(velocity=10, alpha=5),\n)\n\nvlm_aero = vlm.run()\n\nfor key in [\"CL\", \"CD\", \"Cm\"]:\n    print(f\"{key:>2} = {vlm_aero[key]:8.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCL =   0.7056\nCD =   0.0135\nCm =  -0.1283\n```\n:::\n:::\n\n\nAt the same condition, the VLM gives $C_L$ = 0\\.706 versus AeroBuildup's 0\\.787 — agreement to within about 10% in the linear regime, which is typical. The VLM's $C_D$ = 0\\.0135 is *induced drag only* and should never be compared directly against a viscous drag number.\n\nA solved VLM object can draw its own paneling, colored by vortex strength, with streamlines traced through the computed flowfield:\n\n::: {#cell-fig-vlm-mesh .cell execution_count=15}\n``` {.python .cell-code}\nvlm.draw(show_kwargs=dict(jupyter_backend=\"static\", window_size=(1000, 640)));\n```\n\n::: {.cell-output .cell-output-display}\n![The VLM panel mesh of the glider, colored by vortex strength, with computed streamlines. Note the tip vortices rolling off the wing and the downwash field washing over the tail.](06-aircraft-aerodynamics_files/figure-html/fig-vlm-mesh-output-1.png){#fig-vlm-mesh}\n:::\n:::\n\n\nPanel density is controlled by `spanwise_resolution` and `chordwise_resolution` arguments (subdivisions per wing section), trading accuracy against cost.\n\n### Shape optimization teaser: recovering the elliptical wing\n\nBecause the VLM is differentiable, it can serve as the physics inside a shape optimization — no gradient wiring required. Here is the classic textbook problem: *among planar, untwisted wings of fixed span and fixed area, find the chord distribution that minimizes induced drag at a given lift.* Prandtl's lifting-line theory says the answer is an elliptical lift distribution, achieved by an elliptical chord distribution, with induced drag\n\n$$\nC_{D_i} = \\frac{C_L^2}{\\pi \\, A\\!R}.\n$$\n\nWe pose exactly that problem to IPOPT, with the section chords (and the angle of attack needed to hit the lift target) as design variables:\n\n::: {#0f8d4bfd .cell execution_count=16}\n``` {.python .cell-code}\nopti = asb.Opti()\n\nN = 12  # Number of spanwise stations to optimize\nsection_y = np.sinspace(0, 1, N, reverse_spacing=True)  # Cluster near the tip\n\nchords = opti.variable(init_guess=np.ones(N))  # Initial guess: rectangular wing\n\nwing = asb.Wing(\n    symmetric=True,\n    xsecs=[\n        asb.WingXSec(\n            xyz_le=[-0.25 * chords[i], section_y[i], 0],  # Straight quarter-chord line\n            chord=chords[i],\n            airfoil=asb.Airfoil(\"naca0012\"),\n        )\n        for i in range(N)\n    ],\n)\n\nopti.subject_to([\n    chords > 0,\n    wing.area() == 0.25,  # Fixed area (with fixed span => fixed aspect ratio)\n    np.diff(chords) <= 0,  # Chord shrinks toward the tip (regularizes the problem)\n])\n\nalpha_wing = opti.variable(init_guess=5, lower_bound=0, upper_bound=30)\n\nwing_aero = asb.VortexLatticeMethod(\n    airplane=asb.Airplane(wings=[wing]),\n    op_point=asb.OperatingPoint(velocity=1, alpha=alpha_wing),\n    spanwise_resolution=1,  # 1 VLM strip per optimized section\n    chordwise_resolution=6,\n).run()\n\nopti.subject_to(wing_aero[\"CL\"] == 1)  # Fixed lift\nopti.minimize(wing_aero[\"CD\"])\n\nsol = opti.solve(verbose=False)\n\nAR = 2**2 / 0.25  # (span)^2 / area\nCDi_theory = 1**2 / (np.pi * AR)\nprint(f\"CDi (VLM, optimized) : {sol(wing_aero['CD']):.5f}\")\nprint(f\"CDi (lifting-line theory) : {CDi_theory:.5f}\")\nprint(f\"Solved in {sol.stats()['iter_count']} IPOPT iterations\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCDi (VLM, optimized) : 0.01856\nCDi (lifting-line theory) : 0.01989\nSolved in 14 IPOPT iterations\n```\n:::\n:::\n\n\nThe optimizer, knowing nothing about Prandtl, rediscovers the elliptical planform:\n\n::: {#cell-fig-elliptic-wing .cell execution_count=17}\n``` {.python .cell-code}\nimport _common\nimport matplotlib.pyplot as plt\n\nfig, ax = plt.subplots(figsize=(7, 4))\n\ny_analytic = np.linspace(0, 1, 300)\nc_root_analytic = 4 * 0.25 / (np.pi * 2)  # ellipse with S=0.25, b=2\nax.plot(\n    y_analytic,\n    c_root_analytic * np.sqrt(1 - y_analytic**2),\n    color=_common.TEXT_SECONDARY,\n)\n_common.label_line(ax, 0.28, 0.128, \"analytic ellipse\", _common.TEXT_SECONDARY, dy=-0.018)\n\nax.plot(section_y, sol(chords), \".-\", color=_common.SERIES[0], markersize=9)\n_common.label_line(ax, 0.42, 0.155, \"VLM optimum\", _common.SERIES[0], dy=0.006)\n\nax.set_xlabel(\"Spanwise station $y$ [m]\")\nax.set_ylabel(\"Chord $c$ [m]\")\nax.set_ylim(bottom=0)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Chord distribution found by minimizing VLM induced drag at fixed span, area, and lift — compared against the analytic elliptical optimum.](06-aircraft-aerodynamics_files/figure-html/fig-elliptic-wing-output-1.png){#fig-elliptic-wing width=944 height=566}\n:::\n:::\n\n\nThe computed induced drag lands within 7% of the theoretical value; the residual gap is discretization error on both sides (the VLM's finite paneling, and the theory's small-angle and simplified tip treatment). This composability — geometry variables, flow solver, and operating point all inside one optimization problem — is the pattern behind the full design studies in @sec-aerostructural-wing.\n\n## Lifting-line methods {#sec-aircraft-aero-liftingline}\n\nBetween AeroBuildup's empiricism and the VLM's inviscid panels sit two lifting-line methods. Both model each wing as a line of horseshoe vortices (as in classical Prandtl theory, generalized for sweep, dihedral, and multiple surfaces), and both use [NeuralFoil](https://github.com/peterdsharpe/NeuralFoil) — the same neural-network airfoil model from @sec-airfoil-aerodynamics — for 2D viscous sectional data. That gives them something the VLM fundamentally lacks: profile drag and Reynolds-number effects, resolved section by section along the span.\n\nFor these and the validation study, we switch to a cleaner test case: a swept flying wing tested by NACA in the early 1950s (NACA RM A50K27), for which published wind-tunnel data exists.\n\n::: {#ca5e3bfc .cell execution_count=18}\n``` {.python .cell-code}\nairfoil = asb.Airfoil(\n    name=\"n64_1_A612\",\n    coordinates=\"assets/flying-wing/n64_1_A612.dat\",  # NACA 64(1)-A612 section\n)\n\nflying_wing = asb.Airplane(\n    name=\"NACA RM A50K27 flying wing\",\n    xyz_ref=[0.585, 0, 0],  # Moment reference point, matching the report\n    wings=[\n        asb.Wing(\n            name=\"Main Wing\",\n            symmetric=True,\n            xsecs=[\n                asb.WingXSec(xyz_le=[0, 0, 0], chord=0.4120, airfoil=airfoil),\n                asb.WingXSec(xyz_le=[1.1362, 1.5490, 0], chord=0.2060, airfoil=airfoil),\n            ],\n        )\n    ],\n    c_ref=0.32,  # Reference chord used in the report\n)\n\nop_point = asb.OperatingPoint(\n    atmosphere=asb.Atmosphere(altitude=0),\n    velocity=91.3,  # m/s, matching the test's Reynolds number\n)\n\nprint(f\"Aspect ratio : {flying_wing.wings[0].aspect_ratio():.1f}\")\nprint(f\"LE sweep     : {np.arctan2d(1.1362, 1.5490):.1f} deg\")\nprint(f\"Re (c_ref)   : {op_point.reynolds(reference_length=flying_wing.c_ref):.2e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAspect ratio : 10.0\nLE sweep     : 36.3 deg\nRe (c_ref)   : 2.00e+06\n```\n:::\n:::\n\n\n::: {#fig-flying-wing .cell execution_count=19}\n``` {.python .cell-code}\nflying_wing.draw_three_view()\n```\n\n::: {.cell-output .cell-output-display}\n![The NACA RM A50K27 test article: a high-aspect-ratio swept, tapered flying wing — no fuselage, no tail.](06-aircraft-aerodynamics_files/figure-html/fig-flying-wing-output-1.png){#fig-flying-wing-1 width=1422 height=1422}\n:::\n\n::: {#fig-flying-wing-2 .cell-output .cell-output-display execution_count=19}\n```\narray([[<Axes3D: zlabel='$z_g$ [m]'>, <Axes3D: >],\n       [<Axes3D: xlabel='$x_g$ [m]', ylabel='$y_g$ [m]'>, <Axes3D: >]],\n      dtype=object)\n```\n:::\n:::\n\n\n::: {#4061c152 .cell execution_count=20}\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\n<module '_common' from '/tmp/claude-1000/-home-psharpe-gh-AeroSandbox/1ccf6b40-3256-4f8d-9484-ebe00c7e55db/scratchpad/book-staging/_common.py'>\n```\n:::\n:::\n\n\n### `asb.LiftingLine`: quasi-linear\n\n`asb.LiftingLine` solves a single linear system for the spanwise circulation (like a one-panel-chordwise VLM), then evaluates NeuralFoil at each section's local flow condition to add viscous drag and moment. One linear solve plus one network evaluation makes it nearly VLM-cheap while still capturing viscous effects:\n\n::: {#ec1afa12 .cell execution_count=21}\n``` {.python .cell-code}\nop = op_point.copy()\nop.alpha = 5\n\nt_start = time.time()\nll_aero = asb.LiftingLine(\n    airplane=flying_wing,\n    op_point=op,\n).run()\nt_ll = time.time() - t_start\n\nprint(f\"CL = {ll_aero['CL']:.4f}, CD = {ll_aero['CD']:.4f}  ({t_ll:.2f} s)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCL = 0.6036, CD = 0.0160  (0.09 s)\n```\n:::\n:::\n\n\nNote the drag: 0\\.0160 includes profile drag, so it is directly comparable to wind-tunnel measurements — unlike a bare VLM number.\n\n### `asb.NonlinearLiftingLine`: implicit and stall-aware\n\nThe quasi-linear method computes circulation from *linearized* aerodynamics, then applies nonlinear sectional data afterward. `asb.NonlinearLiftingLine` closes that loop: it solves for a circulation distribution that is *self-consistent* with the full nonlinear NeuralFoil polars, so the lift distribution can respond to sections approaching stall. It is an `ImplicitAnalysis` — the governing equations become residual constraints solved by IPOPT:\n\n::: {#cae4b698 .cell execution_count=22}\n``` {.python .cell-code}\nt_start = time.time()\nnlll_aero = asb.NonlinearLiftingLine(\n    airplane=flying_wing,\n    op_point=op,\n    spanwise_resolution=6,  # Downsampled from the default of 8, for speed\n).run()\nt_nlll = time.time() - t_start\n\nprint(f\"CL = {nlll_aero['CL']:.4f}, CD = {nlll_aero['CD']:.4f}  ({t_nlll:.1f} s)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCL = 0.6115, CD = 0.0177  (7.4 s)\n```\n:::\n:::\n\n\nIn the linear regime it reproduces the quasi-linear answer (here, $C_L$ within 1\\.3%), but each analysis costs an iterative solve — 7 s here versus 0\\.09 s. Reach for it when sections are working near their sectional $C_{l,\\max}$ and the lift *distribution* near stall is the question. If you call it standalone via `.run()`, it creates and solves its own `asb.Opti` internally; you can instead pass `opti=` to embed its residuals inside a larger optimization problem, so your design optimization and the aerodynamic solve converge simultaneously.\n\n## Validation: four methods vs. the wind tunnel {#sec-aircraft-aero-validation}\n\nTalk is cheap; let's check all four methods against the NACA wind-tunnel measurements. We sweep angle of attack with each method (AeroBuildup vectorizes; the others loop — an `OperatingPoint` with an array attribute is iterable, which makes the loops tidy), then overlay the published data. For context we also include results from AVL + XFoil, a classic external-tool pairing (@sec-external-tools).\n\n::: {#12c84588 .cell execution_count=23}\n``` {.python .cell-code}\n# --- AeroBuildup: one vectorized call\nab_op = op_point.copy()\nab_op.alpha = np.linspace(-12, 14, 50)\nab_sweep = asb.AeroBuildup(airplane=flying_wing, op_point=ab_op).run()\nab_sweep[\"alpha\"] = ab_op.alpha\n\n\ndef sweep(analysis_class, alphas, **kwargs):\n    \"\"\"Run a (non-vectorized) analysis at each alpha; stack results into arrays.\"\"\"\n    op_sweep = op_point.copy()\n    op_sweep.alpha = alphas\n    runs = [\n        analysis_class(airplane=flying_wing, op_point=op_i, **kwargs).run()\n        for op_i in op_sweep  # a vectorized OperatingPoint is iterable\n    ]\n    result = {k: np.array([r[k] for r in runs]) for k in [\"CL\", \"CD\", \"Cm\"]}\n    result[\"alpha\"] = alphas\n    return result\n\n\nvlm_sweep = sweep(asb.VortexLatticeMethod, np.linspace(-12, 14, 14),\n                  spanwise_resolution=5)\nll_sweep = sweep(asb.LiftingLine, np.linspace(-12, 14, 14))\nnlll_sweep = sweep(asb.NonlinearLiftingLine, np.linspace(-8, 8, 5),\n                   spanwise_resolution=6)  # fewer points: each is an implicit solve\n```\n:::\n\n\n::: {#0c2611ce .cell execution_count=24}\n``` {.python .cell-code}\n# --- Wind-tunnel data (NACA RM A50K27) and AVL+XFoil results\nimport pandas as pd\nfrom scipy import interpolate\n\nwt_CL = pd.read_excel(\"assets/flying-wing/NACA-RM-A50K27.xlsx\", sheet_name=\"CL\")\nwt_CD = pd.read_excel(\"assets/flying-wing/NACA-RM-A50K27.xlsx\", sheet_name=\"CD\")\nwt_Cm = pd.read_excel(\"assets/flying-wing/NACA-RM-A50K27.xlsx\", sheet_name=\"CM\")\n\n# The report gives Cm vs. CL; recover alpha by interpolating the CL-vs-alpha data.\nwt_Cm[\"alpha\"] = interpolate.interp1d(\n    wt_CL[\"CL\"], wt_CL[\"alpha\"], fill_value=\"extrapolate\"\n)(wt_Cm[\"CL\"])\n\navl = pd.read_csv(\"assets/flying-wing/avl_and_xfoil.csv\")  # columns: alpha, CL, CD, Cm\n```\n:::\n\n\n::: {#cell-fig-validation .cell execution_count=25}\n``` {.python .cell-code}\nimport _common\nimport matplotlib.pyplot as plt\n\nmethods = {\n    \"AeroBuildup\": (ab_sweep, _common.SERIES[0]),\n    \"VLM (inviscid)\": (vlm_sweep, _common.SERIES[1]),\n    \"LiftingLine\": (ll_sweep, _common.SERIES[2]),\n    \"NonlinearLiftingLine\": (nlll_sweep, _common.SERIES[4]),\n    \"AVL + XFoil\": (avl, _common.TEXT_SECONDARY),\n}\nwt_format = dict(color=\"black\", linewidth=0, marker=\".\", markersize=6,\n                 label=\"Wind tunnel\", zorder=5)\n\nfig, ax = plt.subplots(3, 1, figsize=(7, 11))\n\nfor name, (data, color) in methods.items():\n    ax[0].plot(data[\"alpha\"], data[\"CL\"], color=color, alpha=0.8, label=name)\n    ax[1].plot(data[\"CD\"], data[\"CL\"], color=color, alpha=0.8)\n    ax[2].plot(data[\"alpha\"], data[\"Cm\"], color=color, alpha=0.8)\n\nax[0].plot(wt_CL[\"alpha\"], wt_CL[\"CL\"], **wt_format)\nax[1].plot(wt_CD[\"CD\"], wt_CD[\"CL\"], **wt_format)\nax[2].plot(wt_Cm[\"alpha\"], wt_Cm[\"Cm\"], **wt_format)\n\nax[0].set_title(\"Lift: all methods agree while the flow stays attached\")\nax[0].set_xlabel(r\"Angle of attack $\\alpha$ [deg]\")\nax[0].set_ylabel(\"$C_L$ [-]\")\nax[0].legend(fontsize=8, loc=\"lower right\")\n\nax[1].set_title(\"Drag: viscous methods bracket the data; the bare VLM cannot\")\nax[1].set_xlabel(\"$C_D$ [-]\")\nax[1].set_ylabel(\"$C_L$ [-]\")\nax[1].set_xlim(0, 1.1 * wt_CD[\"CD\"].max())\n\nax[2].set_title(\"Moment: attached-flow methods miss the stall pitch-break\")\nax[2].set_xlabel(r\"Angle of attack $\\alpha$ [deg]\")\nax[2].set_ylabel(\"$C_m$ [-]\")\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Lift, drag, and moment polars for the NACA RM A50K27 flying wing: AeroSandbox's four built-in methods and AVL+XFoil versus wind-tunnel data.](06-aircraft-aerodynamics_files/figure-html/fig-validation-output-1.png){#fig-validation width=1033 height=1633}\n:::\n:::\n\n\n\n\nQuantitatively, the lift-curve slopes over ±4° come out as:\n\n| Source | $C_{L_\\alpha}$ [1/rad] | vs. wind tunnel |\n|---|---|---|\n| Wind tunnel | 4.33 | — |\n| AeroBuildup | 4.30 | -1% |\n| VLM | 4.44 | +3% |\n| LiftingLine | 3.65 | -16% |\n| NonlinearLiftingLine | 3.64 | -16% |\n\n\nWhat @fig-validation teaches about the fidelity ladder:\n\n- **In the attached-flow regime (roughly $-6° < \\alpha < 7°$), the trends are right across the board — but accuracy differs.** AeroBuildup and the VLM match the measured lift-curve slope to within a few percent; remarkably, AeroBuildup gets there without ever solving a flow equation. The lifting-line methods read about 16% low on lift-curve slope here: this planform's 36° of sweep is exactly where a line-of-horseshoe-vortices model is weakest. Match the method to the geometry — on a high-aspect-ratio, low-sweep wing, the lifting-line methods shine.\n- **Drag separates the methods.** The bare VLM polar hugs the $C_D \\approx C_{D_i}$ boundary — it is missing all profile drag, roughly the entire drag budget at low lift. AeroBuildup and both lifting-line methods, which include viscous sectional data, track the measured drag polar well through the drag bucket and its rise with lift.\n- **Stall breaks everything.** Above $\\alpha \\approx 7°$ the measured lift curve bends over and the measured pitching moment breaks sharply nose-up — the classic tip-stall pitch-up of swept wings, driven by separated flow that none of these attached-flow methods represent. The lesson is not \"find a better fast model\"; it is *know your model's envelope, and constrain your designs to stay inside it* (e.g., impose a $C_L$ margin below stall in your optimization problem).\n\n## Where to go next {#sec-aircraft-aero-next}\n\n- The 2D sectional models that power the lifting-line methods — NeuralFoil's polars, their accuracy envelope, and airfoil shape optimization — are covered in @sec-airfoil-aerodynamics.\n- To anchor these analyses against external codes (AVL, XFoil, OpenVSP) and learn when that's worth the friction, see @sec-external-tools.\n- To see `VortexLatticeMethod` embedded in a full design loop — coupled with structures into a wing aerostructural optimization — jump to @sec-aerostructural-wing.\n\n",
    "supporting": [
      "06-aircraft-aerodynamics_files"
    ],
    "filters": [],
    "includes": {}
  }
}