{
  "hash": "739710e3faae53fd53c3f3503752cf2b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Dynamics Stack\"\n---\n\nThe previous chapter (@sec-optimal-control) taught trajectory optimization on toy systems, where writing out the equations of motion by hand took three lines. Real vehicles are messier: they fly in 3D, they have attitude and angular rates, and their forces arrive in a confusing mix of axis systems. This chapter introduces the AeroSandbox **dynamics stack** — a family of `Dynamics` classes that write the equations of motion for you, let you attach forces in whatever axis frame is most natural, and plug directly into `Opti` as differentiable constraints. You'll learn to pick the right class for your problem's fidelity level, then apply the stack to two showcase problems: a minimum-time quadcopter flip, and a maximum-range engine-out glide of a Cessna 152 with a real aerodynamics model in the loop. At the end, we show that the same classes work *without* an optimizer, as plain equation-of-motion calculators for `scipy` integration and flight-data visualization.\n\n## Why a dynamics engine? {#sec-dynamics-stack}\n\n**The takeaway: you *can* write vehicle dynamics by hand as `Opti` constraints — and you should know how — but a dynamics engine removes the error-prone bookkeeping, and upgrades you to a more accurate integrator for free.**\n\nLet's make that concrete with the simplest trajectory problem in this book: a rocket that must climb vertically to 100 km altitude in 100 seconds, burning as little fuel as possible. The physics is one force balance and one fuel-burn law: acceleration is thrust-over-mass minus gravity, and mass decreases in proportion to thrust (a constant specific impulse of 300 s).\n\n### By hand\n\nWriting the dynamics manually means choosing a discretization and spelling it out. Here we use forward Euler — each state steps forward using the derivative at the *start* of the interval:\n\n$$\n\\Delta z \\approx v(t_1)\\, \\Delta t, \\qquad\n\\Delta v \\approx \\left(\\frac{T(t_1)}{m(t_1)} - g\\right) \\Delta t, \\qquad\n\\Delta m \\approx -\\alpha\\, T(t_1)\\, \\Delta t\n$$\n\n::: {#de53fd5d .cell execution_count=1}\n``` {.python .cell-code}\nimport aerosandbox as asb\nimport aerosandbox.numpy as np\n\nopti = asb.Opti()\n\nN = 100  # number of discretization points\ntime = np.linspace(0, 100, N)  # sec\n\nmass_initial = 500e3  # kg (a 500-metric-ton rocket)\nz_final = 100e3  # m\ng = 9.81  # m/s^2\nalpha_fuel = 1 / (300 * g)  # kg of fuel per N-s of impulse (i.e., Isp = 300 s)\n\naltitude = opti.variable(init_guess=np.linspace(0, z_final, N))\nvelocity = opti.variable(init_guess=z_final / 100, n_vars=N)\nmass = opti.variable(init_guess=mass_initial, n_vars=N)\nthrust = opti.variable(init_guess=g * mass_initial, n_vars=N, lower_bound=0)\n\nopti.subject_to(\n    [  # The dynamics, discretized manually with forward Euler:\n        np.diff(altitude) == velocity[:-1] * np.diff(time),\n        np.diff(velocity) == (thrust[:-1] / mass[:-1] - g) * np.diff(time),\n        np.diff(mass) == -alpha_fuel * thrust[:-1] * np.diff(time),\n    ]\n)\n\nopti.subject_to(\n    [\n        altitude[0] == 0,\n        velocity[0] == 0,\n        mass[0] == mass_initial,\n        altitude[-1] == z_final,\n        mass >= 0,\n    ]\n)\n\nopti.minimize(-mass[-1])  # maximize final mass == minimize fuel burn\n\nsol_manual = opti.solve(verbose=False)\nfuel_manual = mass_initial - sol_manual(mass[-1])\nprint(f\"Fuel burned (manual Euler, N={N}): {fuel_manual / 1e3:.1f} metric tons\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFuel burned (manual Euler, N=100): 210.0 metric tons\n```\n:::\n:::\n\n\nThis works, and for a 1D problem it's perfectly reasonable. But notice what you had to get right by hand: the discretization scheme, the indexing (`[:-1]` everywhere), and the sign conventions. In 3D, with attitude dynamics, this approach balloons to hundreds of lines of quaternion or Euler-angle algebra — all of it an opportunity for silent sign errors.\n\n### With the dynamics engine\n\nThe same problem with `asb.DynamicsPointMass1DVertical`:\n\n::: {#b5d48591 .cell execution_count=2}\n``` {.python .cell-code}\nopti = asb.Opti()\ntime = np.linspace(0, 100, N)\n\ndyn = asb.DynamicsPointMass1DVertical(\n    mass_props=asb.MassProperties(\n        mass=opti.variable(init_guess=mass_initial, n_vars=N)\n    ),\n    z_e=opti.variable(init_guess=np.linspace(0, -z_final, N)),\n    w_e=opti.variable(init_guess=-z_final / 100, n_vars=N),\n)\n\nthrust = opti.variable(init_guess=g * mass_initial, n_vars=N, lower_bound=0)\ndyn.add_force(Fz=-thrust)  # Earth axes are North-East-Down: \"up\" is -z!\ndyn.add_gravity_force(g=g)\n\ndyn.constrain_derivatives(opti, time)  # <-- the equations of motion, written for you\n\n# Fuel burn isn't part of the standard point-mass state, so we add it ourselves:\nopti.constrain_derivative(\n    derivative=-alpha_fuel * thrust,\n    variable=dyn.mass_props.mass,\n    with_respect_to=time,\n)\n\nopti.subject_to(\n    [\n        dyn.z_e[0] == 0,\n        dyn.w_e[0] == 0,\n        dyn.mass_props.mass[0] == mass_initial,\n        dyn.z_e[-1] == -z_final,\n        dyn.mass_props.mass >= 0,\n    ]\n)\n\nopti.minimize(-dyn.mass_props.mass[-1])\n\nsol = opti.solve(verbose=False)\ndyn = sol(dyn)  # substitutes optimized values into the Dynamics object, in-place\n\nfuel_engine = mass_initial - dyn.mass_props.mass[-1]\nprint(f\"Fuel burned (dynamics engine, N={N}): {fuel_engine / 1e3:.1f} metric tons\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nFuel burned (dynamics engine, N=100): 201.7 metric tons\n```\n:::\n:::\n\n\nThe workflow, which every problem in this chapter repeats, is:\n\n1. **Instantiate** a `Dynamics` class, passing `Opti` variables (or plain numbers) as the state variables.\n2. **Add forces** with `dyn.add_force()` (and moments with `dyn.add_moment()`, for rigid-body classes), in whatever axis system each force is naturally expressed in. `dyn.add_gravity_force()` is a shorthand for the most common one.\n3. **`dyn.constrain_derivatives(opti, time)`** — this computes the state derivatives from the accumulated forces and constrains the discretized trajectory to obey them, exactly like the `opti.constrain_derivative()` calls of @sec-optimal-control, just applied to every state variable at once.\n4. Add boundary conditions and an objective, solve, and call **`sol(dyn)`** to push the solved values back into the object for post-processing.\n\n::: {#3542fa20 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](12-dynamics-stack_files/figure-html/cell-4-output-1.png){width=1036 height=736}\n:::\n:::\n\n\nThe optimal strategy is the classic one: burn hard early (while you're heavy and every second spent hovering costs fuel), then cut the engine and coast to apogee.\n\n### Same physics, different answers?\n\nLook closely at the two fuel burns: 210\\.0 tons by hand versus 201\\.7 tons with the engine — a 8\\.2-ton disagreement from the *same physics on the same grid*. The difference is the integrator: our manual version used forward Euler (first-order accurate), while `constrain_derivatives()` defaults to trapezoidal integration (second-order accurate), which averages the derivative across each interval. Refining the grid shows which one to believe:\n\n::: {#1fe32add .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show the grid-refinement reference computation\"}\ndef solve_rocket_trapezoidal(N_ref):\n    opti = asb.Opti()\n    time = np.linspace(0, 100, N_ref)\n    z = opti.variable(init_guess=np.linspace(0, z_final, N_ref))\n    v = opti.variable(init_guess=z_final / 100, n_vars=N_ref)\n    m = opti.variable(init_guess=mass_initial, n_vars=N_ref)\n    T = opti.variable(init_guess=g * mass_initial, n_vars=N_ref, lower_bound=0)\n    opti.constrain_derivative(v, z, time)\n    opti.constrain_derivative(T / m - g, v, time)\n    opti.constrain_derivative(-alpha_fuel * T, m, time)\n    opti.subject_to([z[0] == 0, v[0] == 0, m[0] == mass_initial, z[-1] == z_final, m >= 0])\n    opti.minimize(-m[-1])\n    return mass_initial - opti.solve(verbose=False)(m[-1])\n\n\nfuel_ref = solve_rocket_trapezoidal(N_ref=2000)\n\nerr_manual = fuel_manual - fuel_ref\nerr_engine = fuel_engine - fuel_ref\nprint(f\"Refined-grid reference fuel burn:  {fuel_ref / 1e3:.1f} tons\")\nprint(f\"Error, manual Euler at N={N}:      {err_manual / 1e3:+.1f} tons ({err_manual / fuel_ref:+.1%})\")\nprint(f\"Error, trapezoidal at N={N}:       {err_engine / 1e3:+.1f} tons ({err_engine / fuel_ref:+.1%})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRefined-grid reference fuel burn:  199.0 tons\nError, manual Euler at N=100:      +10.9 tons (+5.5%)\nError, trapezoidal at N=100:       +2.7 tons (+1.3%)\n```\n:::\n:::\n\n\nAt identical grid resolution, the trapezoidal answer lands roughly 4× closer to the refined-grid reference. That's the \"for free\" part: the dynamics engine doesn't just save typing, it defaults you into a better discretization. (For the systematic way to run refinement studies like this, see @sec-optimal-control.)\n\n## The `Dynamics` family {#sec-dynamics-stack-family}\n\n**The takeaway: pick the class whose *state parameterization* matches your problem — point-mass vs. rigid-body, 1D/2D/3D, Cartesian vs. speed-angle — and everything downstream (forces, frames, constraints) works identically.**\n\nAerospace dynamics problems nearly all reduce to the same skeleton: a (roughly) rigid body moving through 3D space, sometimes simplified to 2D or 1D. Rather than one monolithic simulator, AeroSandbox provides a family of classes, each implementing the equations of motion for one combination of fidelity and state parameterization. The full 3D rigid-body class implements the standard nonlinear equations of motion (following Chapter 9 of Drela's *Flight Vehicle Aerodynamics*); the others are progressively-reduced special cases. All of them share the interface you just saw: `state`, `add_force()`, `constrain_derivatives()`, `state_derivatives()`.\n\nHere is the whole family — this table is generated live from the library, so it always matches your installed version:\n\n::: {#951e1d95 .cell execution_count=5}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show the code that generates this table\"}\nimport pandas as pd\n\ndynamics_classes = [\n    asb.DynamicsPointMass1DHorizontal,\n    asb.DynamicsPointMass1DVertical,\n    asb.DynamicsPointMass2DCartesian,\n    asb.DynamicsPointMass2DSpeedGamma,\n    asb.DynamicsPointMass3DCartesian,\n    asb.DynamicsPointMass3DSpeedGammaTrack,\n    asb.DynamicsRigidBody2DBody,\n    asb.DynamicsRigidBody3DBodyEuler,\n]\n\ntable = pd.DataFrame(\n    [\n        {\n            \"Class\": cls.__name__,\n            \"Model\": \"Rigid body\" if \"RigidBody\" in cls.__name__ else \"Point mass\",\n            \"States\": \", \".join(cls().state.keys()),\n            \"Controls\": \", \".join(cls().control_variables.keys()),\n        }\n        for cls in dynamics_classes\n    ]\n)\ntable\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Class</th>\n      <th>Model</th>\n      <th>States</th>\n      <th>Controls</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>DynamicsPointMass1DHorizontal</td>\n      <td>Point mass</td>\n      <td>x_e, u_e</td>\n      <td>Fx_e</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>DynamicsPointMass1DVertical</td>\n      <td>Point mass</td>\n      <td>z_e, w_e</td>\n      <td>Fz_e</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>DynamicsPointMass2DCartesian</td>\n      <td>Point mass</td>\n      <td>x_e, z_e, u_e, w_e</td>\n      <td>alpha, Fx_e, Fz_e</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>DynamicsPointMass2DSpeedGamma</td>\n      <td>Point mass</td>\n      <td>x_e, z_e, speed, gamma</td>\n      <td>alpha, Fx_w, Fz_w</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>DynamicsPointMass3DCartesian</td>\n      <td>Point mass</td>\n      <td>x_e, y_e, z_e, u_e, v_e, w_e</td>\n      <td>alpha, beta, bank, Fx_e, Fy_e, Fz_e</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>DynamicsPointMass3DSpeedGammaTrack</td>\n      <td>Point mass</td>\n      <td>x_e, y_e, z_e, speed, gamma, track</td>\n      <td>alpha, beta, bank, Fx_w, Fy_w, Fz_w</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>DynamicsRigidBody2DBody</td>\n      <td>Rigid body</td>\n      <td>x_e, z_e, u_b, w_b, theta, q</td>\n      <td>Fx_b, Fz_b, My_b</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>DynamicsRigidBody3DBodyEuler</td>\n      <td>Rigid body</td>\n      <td>x_e, y_e, z_e, u_b, v_b, w_b, phi, theta, psi,...</td>\n      <td>Fx_b, Fy_b, Fz_b, Mx_b, My_b, Mz_b, hx_b, hy_b...</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nReading the names: `DynamicsPointMass2DSpeedGamma` is a **point mass**, in **2D**, with velocity parameterized as **speed and flight-path angle** ($V$, $\\gamma$) rather than Cartesian components. The \"Controls\" column lists both true control inputs (forces $F$, moments $M$) and *indirect* controls like `alpha` — quantities that aren't states (they have no time derivative in the model) but that you'll typically make decision variables so the optimizer can steer with them.\n\nThe `mass_props` argument accepts an `asb.MassProperties` object (mass, CG location, and — for the rigid-body classes — the full inertia tensor; see @sec-geometry-mass). Point-mass classes only use the mass; rigid-body classes use everything.\n\n### Three axis systems {#sec-dynamics-stack-frames}\n\nEvery force on an aircraft is most naturally expressed in *some* frame: gravity acts straight down, thrust acts along the airframe, and lift and drag are defined relative to the incoming wind. The dynamics stack lets you state each force in its natural frame and handles all rotations internally. The three frames you'll use constantly:\n\n* **Earth axes** (`\"earth\"`): fixed to the ground, using the **North-East-Down (NED)** convention. This trips up everyone at least once: $z_e$ points **down**, so altitude is $-z_e$ (every `Dynamics` class provides `dyn.altitude` so you never have to remember). NED assumes a locally-flat Earth.\n* **Body axes** (`\"body\"`): painted onto the vehicle. $x_b$ points forward out the nose, $y_b$ out the right wing, $z_b$ down through the belly.\n* **Wind axes** (`\"wind\"`): aligned with the velocity vector. $x_w$ points *into* the relative wind (i.e., along the direction of flight), $z_w$ points downward perpendicular to it. Drag is therefore a force in the $-x_w$ direction, and lift is in the $-z_w$ direction — both negated, another classic sign trap.\n\n::: {#cell-fig-12-frames .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![The three axis systems of the dynamics stack, in a 2D side view. Pitch angle θ orients the body frame, flight-path angle γ orients the wind frame (which follows the velocity vector), and angle of attack α = θ − γ separates them. Note that all three z-axes point generally *downward* — Earth axes are North-East-Down.](12-dynamics-stack_files/figure-html/fig-12-frames-output-1.png){#fig-12-frames width=974 height=425 fig-alt='Vector diagram showing an aircraft symbol with three coordinate frames: gray Earth axes (x_e right, z_e down), blue body axes rotated up by the pitch angle theta, and green wind axes aligned with the velocity vector at flight path angle gamma. Angle arcs mark gamma between the horizon and velocity vector, and alpha between the velocity vector and the body x-axis.'}\n:::\n:::\n\n\nTwo methods put these frames to work:\n\n* `dyn.add_force(Fx=..., Fy=..., Fz=..., axes=\"wind\")` accumulates a force expressed in any frame (same for `add_moment` on rigid-body classes). You saw `axes=\"earth\"` implicitly in `add_gravity_force()`.\n* `dyn.convert_axes(x, y, z, from_axes=\"body\", to_axes=\"earth\")` converts any vector between frames, using the instance's current attitude. (Two more frames, `\"geometry\"` and `\"stability\"`, exist for interfacing with geometry and aerodynamics tools.)\n\nFinally, every `Dynamics` instance exposes **`dyn.op_point`**: an `asb.OperatingPoint` built from the current state, complete with an `Atmosphere` evaluated at the instance's altitude (see @sec-apw-operating-point). This one property is the bridge between dynamics and aerodynamics — you can hand it straight to an aero model, as we'll do in the Cessna case below.\n\n### Choosing a fidelity level {#sec-dynamics-stack-fidelity}\n\nWhich class should you use? Match the *timescales*:\n\n* **Maneuver problems** (seconds): if the vehicle's rotational dynamics matter — a quadcopter flip, a fighter pull-up, spin recovery — use a **rigid-body** class. You get attitude ($\\phi, \\theta, \\psi$) and angular rates ($p, q, r$) as states, driven by moments through the full inertia tensor.\n* **Mission and performance problems** (minutes to hours): an airplane's short-period and lateral modes settle in seconds, far faster than the energy management you care about. A **point-mass** class discards them: angular rates are assumed zero, and attitude becomes a *control* you prescribe (via `alpha`, `bank`) rather than a state you integrate. For longitudinal problems, `DynamicsPointMass2DSpeedGamma` — states $x_e, z_e, V, \\gamma$ — is the workhorse; its 3D sibling `DynamicsPointMass3DSpeedGammaTrack` adds a heading (\"track\") state and a bank-angle control for problems like engine-out turnbacks.\n\nThis is the same physical judgment as choosing between an Euler code and a panel method in aerodynamics: not \"which model is best,\" but \"which model is the cheapest one that resolves the physics my decision depends on.\"\n\n## Case study 1: a minimum-time quadcopter flip {#sec-dynamics-stack-quadcopter}\n\n**The takeaway: with a rigid-body dynamics class, a genuinely aggressive optimal-control problem — a full 360° flip — is about 40 lines of code.**\n\nConsider an idealized 2D quadcopter: a 0.1 kg bar, 0.1 m wide, with one rotor at each end. Each rotor produces 0 to 1 N of thrust along the body $-z_b$ axis (i.e., \"up\" when the vehicle is level), so the vehicle has a thrust-to-weight ratio of about 2. Equal thrusts accelerate it; *differential* thrust creates a pitching moment about the center — that's the only way it can rotate.\n\nFirst, a drawing helper so we can see what the vehicle is doing (matplotlib patches; nothing AeroSandbox-specific — feel free to skip):\n\n::: {#506f5670 .cell execution_count=7}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show the quadcopter-drawing helper\"}\nimport _common\nimport matplotlib as mpl\nimport matplotlib.pyplot as plt\n\n# Single-hue sequential colormap for thrust magnitude (light = low, dark = high):\nthrust_cmap = mpl.colors.LinearSegmentedColormap.from_list(\n    \"thrust\", [\"#d6e5f7\", \"#0b3c74\"]\n)\nthrust_norm = mpl.colors.Normalize(vmin=0, vmax=1)\n\n\ndef draw_quad_trajectory(\n    dyn, left_thrust, right_thrust, interval=5, magnify=1.0, figsize=(8, 4.5)\n):\n    \"\"\"Draws the quadcopter every `interval`-th timestep along its trajectory,\n    with rotors colored by their instantaneous thrust.\"\"\"\n    fig, ax = plt.subplots(figsize=figsize)\n    ax.plot(dyn.x_e, -dyn.z_e, color=_common.GRID, lw=1.5, zorder=1)  # path\n\n    for i in range(0, len(dyn), interval):\n        d = dyn[i]  # Dynamics instances are indexable: one snapshot in time\n        xform = (\n            mpl.transforms.Affine2D()\n            .scale(0.1 * magnify)  # vehicle is 0.1 m wide\n            .rotate(d.theta)\n            .translate(d.x_e, -d.z_e)\n            + ax.transData\n        )\n        patches = [\n            mpl.patches.Rectangle((-0.5, -0.06), 1.0, 0.12, color=_common.TEXT_PRIMARY),\n            mpl.patches.Ellipse(\n                (-0.5, 0.16), 0.62, 0.17, color=thrust_cmap(thrust_norm(left_thrust[i]))\n            ),\n            mpl.patches.Ellipse(\n                (0.5, 0.16), 0.62, 0.17, color=thrust_cmap(thrust_norm(right_thrust[i]))\n            ),\n        ]\n        for patch in patches:\n            patch.set_transform(xform)\n            patch.set_zorder(5)\n            ax.add_patch(patch)\n\n    fig.colorbar(\n        mpl.cm.ScalarMappable(norm=thrust_norm, cmap=thrust_cmap),\n        ax=ax, label=\"Rotor thrust [N]\", shrink=0.85,\n    )\n    ax.set_aspect(\"equal\", adjustable=\"box\")\n    ax.set_xlabel(\"$x_e$ [m]\")\n    ax.set_ylabel(\"Altitude $-z_e$ [m]\")\n    if magnify != 1:\n        ax.annotate(\n            f\"Vehicle drawn {magnify:g}× larger for visibility.\",\n            xy=(0.5, 0.02), xycoords=\"axes fraction\", ha=\"center\", fontsize=8,\n            color=_common.TEXT_SECONDARY,\n        )\n    return fig, ax\n\n\nquad_mass_props = asb.MassProperties(\n    mass=0.1,  # kg\n    Iyy=0.5 * 0.1 * 0.1**2,  # pitch inertia [kg·m²]; Ixx/Izz don't matter in 2D\n    Ixx=1, Izz=1,\n)\n```\n:::\n\n\n### Simulation is just optimization with nothing left to choose\n\nBefore optimizing anything, note a useful degenerate case: if you prescribe *all* the control inputs and the initial state, the \"optimization problem\" has exactly as many constraints as unknowns — there are no degrees of freedom left, and no objective is needed. `opti.solve()` then simply *integrates the trajectory* (it solves the discretized equations of motion as a root-finding problem — the same trick as the feasibility problems of @sec-solvers-feasibility). Here's one second of flight with slightly asymmetric rotor thrusts:\n\n::: {#466ddbb8 .cell execution_count=8}\n``` {.python .cell-code}\nopti = asb.Opti()\n\nN = 150\ntime = np.linspace(0, 1, N)  # sec\n\nleft_thrust = 0.85 * np.ones(N)  # N (prescribed, not a variable!)\nright_thrust = 0.78 * np.ones(N)\n\ndyn = asb.DynamicsRigidBody2DBody(\n    mass_props=quad_mass_props,\n    x_e=opti.variable(init_guess=0, n_vars=N),\n    z_e=opti.variable(init_guess=0, n_vars=N),\n    u_b=opti.variable(init_guess=0, n_vars=N),\n    w_b=opti.variable(init_guess=0, n_vars=N),\n    theta=opti.variable(init_guess=0, n_vars=N),\n    q=opti.variable(init_guess=0, n_vars=N),\n)\n\ndyn.add_force(Fz=-(left_thrust + right_thrust), axes=\"body\")  # rotors push \"up\"\ndyn.add_moment(My=(right_thrust - left_thrust) * 0.1 / 2)  # differential thrust\ndyn.add_gravity_force()\n\ndyn.constrain_derivatives(opti, time)\n\nopti.subject_to(  # initial condition: at rest at the origin\n    [dyn.x_e[0] == 0, dyn.z_e[0] == 0, dyn.u_b[0] == 0,\n     dyn.w_b[0] == 0, dyn.theta[0] == 0, dyn.q[0] == 0]\n)\n\nsol = opti.solve(verbose=False)  # no objective: this is pure simulation\ndyn = sol(dyn)\n```\n:::\n\n\n::: {#cell-fig-12-quad-openloop .cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![One second of open-loop flight with mismatched rotor thrusts (left 0.85 N, right 0.78 N). Thrust above weight lofts the vehicle at first, but the imbalance steadily torques it over; once tipped, the thrust vector swings sideways and the quad careens off downrange — anyone's first flight on a real quadcopter.](12-dynamics-stack_files/figure-html/fig-12-quad-openloop-output-1.png){#fig-12-quad-openloop width=1011 height=493 fig-alt='Trajectory plot of a small 2D quadcopter drawn at successive snapshots. It rises from the origin while progressively tipping over, arcs over a peak about 1.3 meters up and continues pitching as it accelerates downrange, ending in a descending, steeply-tipped attitude around 3 meters from the start. Rotor colors show constant slightly-mismatched thrusts.'}\n:::\n:::\n\n\n### Now, the flip\n\nTime to fly it properly. The mission: start at rest at the origin, end at rest 1 m to the right, having completed one full 360° pitch flip on the way — in minimum time. Both rotor thrusts become decision variables (bounded 0–1 N), and so does the final time itself (a *free-final-time* problem, exactly as in @sec-optimal-control):\n\n::: {#83327494 .cell execution_count=10}\n``` {.python .cell-code}\nopti = asb.Opti()\n\nN = 80\ntime_final = opti.variable(init_guess=1, lower_bound=0)\ntime = np.linspace(0, time_final, N)\n\nleft_thrust = opti.variable(init_guess=0.7, n_vars=N, lower_bound=0, upper_bound=1)\nright_thrust = opti.variable(init_guess=0.6, n_vars=N, lower_bound=0, upper_bound=1)\n\ndyn = asb.DynamicsRigidBody2DBody(\n    mass_props=quad_mass_props,\n    x_e=opti.variable(init_guess=np.linspace(0, 1, N)),\n    z_e=opti.variable(init_guess=0, n_vars=N),\n    u_b=opti.variable(init_guess=0, n_vars=N),\n    w_b=opti.variable(init_guess=0, n_vars=N),\n    theta=opti.variable(init_guess=np.linspace(0, -2 * np.pi, N)),\n    q=opti.variable(init_guess=0, n_vars=N),\n)\n\ndyn.add_force(Fz=-(left_thrust + right_thrust), axes=\"body\")\ndyn.add_moment(My=(right_thrust - left_thrust) * 0.1 / 2)\ndyn.add_gravity_force()\n\ndyn.constrain_derivatives(opti, time)\n\nopti.subject_to(  # start: at rest at the origin\n    [dyn.x_e[0] == 0, dyn.z_e[0] == 0, dyn.u_b[0] == 0,\n     dyn.w_b[0] == 0, dyn.theta[0] == 0, dyn.q[0] == 0]\n)\nopti.subject_to(  # end: at rest at (1, 0), having flipped through -360°\n    [dyn.x_e[-1] == 1, dyn.z_e[-1] == 0, dyn.u_b[-1] == 0,\n     dyn.w_b[-1] == 0, dyn.theta[-1] == np.radians(-360), dyn.q[-1] == 0]\n)\n\nopti.minimize(time_final)\n\nsol = opti.solve(verbose=False)\ndyn = sol(dyn)\nflip_time = sol(time_final)\nprint(f\"Minimum-time flip completed in {flip_time:.3f} sec.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMinimum-time flip completed in 0.826 sec.\n```\n:::\n:::\n\n\nNote the initial guess for `theta`: `np.linspace(0, -2 * np.pi, N)` sketches \"rotate once, nose-forward\" for the optimizer. Free-final-time flip problems are nonconvex — guess `+2π` instead and you'll converge to an equally-valid *backflip*. Providing a rough storyboard of the maneuver as the initial guess is standard practice (see @sec-optimal-control).\n\n::: {#cell-fig-12-quad-flip .cell execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![The minimum-time flip. The quadcopter leaps up and to the right, commits to the rotation, completes most of the flip near the top of its hop, and catches itself at the far boundary condition.](12-dynamics-stack_files/figure-html/fig-12-quad-flip-output-1.png){#fig-12-quad-flip width=997 height=493 fig-alt='Trajectory of the quadcopter performing a forward flip: snapshots show it rising from the origin, rotating nose-down through inverted flight at the top of an arc about half a meter up, then descending and leveling out at one meter downrange. Rotor colors alternate between near-zero and maximum thrust.'}\n:::\n:::\n\n\n::: {#cell-fig-12-quad-thrust .cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![Rotor thrust histories for the flip. The solution is essentially bang-bang: each rotor slams between its bounds, and the two commands mirror each other to torque the vehicle into, and then out of, the rotation.](12-dynamics-stack_files/figure-html/fig-12-quad-thrust-output-1.png){#fig-12-quad-thrust width=1024 height=662 fig-alt='Two-panel plot of left and right rotor thrust versus time. Both traces switch sharply between 0 and 1 Newton several times during the maneuver, with the left and right commands roughly mirroring each other.'}\n:::\n:::\n\n\nNobody told the optimizer to use bang-bang control — it *discovered* that saturating the actuators is time-optimal, which is exactly what optimal-control theory predicts for this class of problem. This entire study is roughly 40 lines of model code, and it solves in seconds.\n\n## Case study 2: engine-out glide of a Cessna 152 {#sec-dynamics-stack-cessna}\n\n**The takeaway: `dyn.op_point` lets you drop a full physics-based aerodynamics model into the trajectory optimization loop — the optimizer then rediscovers, on its own, what flight instructors teach about engine-out glides.**\n\nPicture a Cessna 152 cruising at 107 knots, 1000 m above central Massachusetts, when the engine sputters and dies. Two questions matter immediately: how far can it glide, and how should the pilot fly to achieve that? This is a *mission-performance* problem — minutes long, no aerobatics — so per @sec-dynamics-stack-fidelity we use the 2D point-mass class with speed–flight-path-angle states, and the angle of attack becomes the pilot's control input.\n\nUnlike the quadcopter (whose \"aerodynamics\" was two thrust numbers), this problem needs a real force model. We define the airplane's geometry with `asb.Airplane` (the subject of @sec-geometry-tree — the details are collapsed below) and let `asb.AeroBuildup` (@sec-aircraft-aero-aerobuildup) predict its lift and drag.\n\n::: {#21b836a2 .cell execution_count=13}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Show the Cessna 152 geometry definition\"}\nimport aerosandbox as asb\nimport aerosandbox.numpy as np\nfrom aerosandbox.tools import units as u\n\n\ndef ft(feet, inches=0.0):  # converts feet (and inches) to meters\n    return feet * u.foot + inches * u.inch\n\n\nairplane = asb.Airplane(\n    name=\"Cessna 152\",\n    wings=[\n        asb.Wing(\n            name=\"Wing\",\n            xsecs=[\n                asb.WingXSec(\n                    xyz_le=[0, 0, 0], chord=ft(5, 4), airfoil=asb.Airfoil(\"naca2412\")\n                ),\n                asb.WingXSec(\n                    xyz_le=[0, ft(7), ft(7) * np.sind(1)],\n                    chord=ft(5, 4),\n                    airfoil=asb.Airfoil(\"naca2412\"),\n                ),\n                asb.WingXSec(\n                    xyz_le=[\n                        ft(4, 3 / 4) - ft(3, 8 + 1 / 2),\n                        ft(33, 4) / 2,\n                        ft(33, 4) / 2 * np.sind(1),\n                    ],\n                    chord=ft(3, 8 + 1 / 2),\n                    airfoil=asb.Airfoil(\"naca0012\"),\n                ),\n            ],\n            symmetric=True,\n        ),\n        asb.Wing(\n            name=\"Horizontal Stabilizer\",\n            xsecs=[\n                asb.WingXSec(\n                    xyz_le=[0, 0, 0],\n                    chord=ft(3, 8),\n                    airfoil=asb.Airfoil(\"naca0012\"),\n                    twist=-2,\n                ),\n                asb.WingXSec(\n                    xyz_le=[ft(1), ft(10) / 2, 0],\n                    chord=ft(2, 4 + 3 / 8),\n                    airfoil=asb.Airfoil(\"naca0012\"),\n                    twist=-2,\n                ),\n            ],\n            symmetric=True,\n        ).translate([ft(13, 3), 0, ft(-2)]),\n        asb.Wing(\n            name=\"Vertical Stabilizer\",\n            xsecs=[\n                asb.WingXSec(\n                    xyz_le=[ft(-5), 0, 0],\n                    chord=ft(8, 8),\n                    airfoil=asb.Airfoil(\"naca0012\"),\n                ),\n                asb.WingXSec(\n                    xyz_le=[ft(0), 0, ft(1)],\n                    chord=ft(3, 8),\n                    airfoil=asb.Airfoil(\"naca0012\"),\n                ),\n                asb.WingXSec(\n                    xyz_le=[ft(0, 8), 0, ft(5)],\n                    chord=ft(2, 8),\n                    airfoil=asb.Airfoil(\"naca0012\"),\n                ),\n            ],\n        ).translate([ft(16, 11) - ft(3, 8), 0, ft(-2)]),\n    ],\n    fuselages=[\n        asb.Fuselage(\n            xsecs=[\n                asb.FuselageXSec(xyz_c=[0, 0, ft(-1)], radius=0),\n                asb.FuselageXSec(xyz_c=[0, 0, ft(-1)], radius=ft(1.5), shape=4),\n                asb.FuselageXSec(xyz_c=[ft(3), 0, ft(-0.85)], radius=ft(1.7), shape=4),\n                asb.FuselageXSec(xyz_c=[ft(5), 0, ft(0)], radius=ft(2.7), shape=3),\n                asb.FuselageXSec(xyz_c=[ft(10, 4), 0, ft(0.3)], radius=ft(2.3), shape=3),\n                asb.FuselageXSec(xyz_c=[ft(21, 11), 0, ft(0.8)], radius=ft(0.3)),\n            ]\n        )\n        .translate([ft(-5), 0, ft(-3)])\n        .subdivide_sections(2)\n    ],\n)\n```\n:::\n\n\n::: {#3b76ae85 .cell execution_count=14}\n``` {.python .cell-code}\nairplane.draw_three_view()\n```\n\n::: {.cell-output .cell-output-display}\n![](12-dynamics-stack_files/figure-html/cell-15-output-1.png){width=1896 height=1896}\n:::\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\narray([[<Axes3D: zlabel='$z_g$ [m]'>, <Axes3D: >],\n       [<Axes3D: xlabel='$x_g$ [m]', ylabel='$y_g$ [m]'>, <Axes3D: >]],\n      dtype=object)\n```\n:::\n:::\n\n\n::: {#e4dacfd7 .cell execution_count=15}\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\n<module '_common' from '/tmp/claude-1000/-home-psharpe-gh-AeroSandbox/1ccf6b40-3256-4f8d-9484-ebe00c7e55db/scratchpad/book-staging/_common.py'>\n```\n:::\n:::\n\n\n### How well does it glide?\n\nBefore optimizing a trajectory, sanity-check the aerodynamics with a quick polar sweep. `AeroBuildup` is fully vectorized, so all 300 angles of attack evaluate in one call:\n\n::: {#d30f3783 .cell execution_count=16}\n``` {.python .cell-code}\nalpha_sweep = np.linspace(-15, 15, 300)  # deg\naero_sweep = asb.AeroBuildup(\n    airplane=airplane,\n    op_point=asb.OperatingPoint(velocity=107 * u.knot, alpha=alpha_sweep),\n).run()\n\nLD = aero_sweep[\"CL\"] / aero_sweep[\"CD\"]\nLD_max = np.max(LD)\nalpha_LD_max = alpha_sweep[np.argmax(LD)]\nprint(f\"Predicted best glide ratio: {LD_max:.1f}, at alpha = {alpha_LD_max:.1f} deg\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPredicted best glide ratio: 18.7, at alpha = 3.1 deg\n```\n:::\n:::\n\n\n::: {#cell-fig-12-cessna-polars .cell execution_count=17}\n\n::: {.cell-output .cell-output-display}\n![AeroBuildup polars for the Cessna 152 model at 107 knots. Lift is linear until stall onset; drag grows quadratically away from its minimum; and their ratio peaks at the best-glide angle of attack (marked).](12-dynamics-stack_files/figure-html/fig-12-cessna-polars-output-1.png){#fig-12-cessna-polars width=1033 height=1035 fig-alt='Three vertically stacked plots versus angle of attack from -15 to 15 degrees: lift coefficient rising roughly linearly through about 1.5, drag coefficient in a bucket shape with minimum near zero alpha, and lift-to-drag ratio peaking near 5 degrees alpha with the maximum marked by a dot and label.'}\n:::\n:::\n\n\n::: {.callout-warning}\n## Trust, but calibrate\n\nAeroBuildup predicts a best glide ratio of 18\\.7; the FAA quotes roughly **9:1** for a real, engine-out Cessna 152. The model isn't broken — our *inputs* are idealized. A stopped, non-feathering propeller is a large drag brake; we omitted the landing gear, wing struts, cooling-air momentum losses, antennas, rivets, and control-surface gaps. Per Hoerner's *Fluid-Dynamic Drag*, such \"everything else\" items can roughly double a light aircraft's profile drag. The lesson generalizes: a clean-geometry aero model gives you the clean-geometry answer, and closing the gap to flight data is a drag-accounting exercise, not a solver problem. For this study the *shape* of the optimal trajectory is unaffected; just mentally halve the range numbers.\n:::\n\n### The trajectory problem\n\nNow the optimization: maximize final downrange distance $x_e$, starting from 1000 m altitude at cruise speed. The final time is free (we let the optimizer stretch the time grid via a `log_transform`ed variable, since durations are strictly positive — see @sec-robust-scaling). The one genuinely new line is passing `dyn.op_point` — a *symbolic* operating point, containing the optimizer's current guesses of speed, altitude, and angle of attack at all 50 time nodes — directly into `AeroBuildup`. The entire aerodynamics model is thereby traced into the optimization graph, derivatives and all.\n\n::: {#c22f93e8 .cell execution_count=18}\n``` {.python .cell-code}\nfrom time import perf_counter\n\nopti = asb.Opti()\n\n### Time discretization: free final time, cosine-spaced to resolve both ends\nN = 50\ntime = np.cosspace(0, opti.variable(init_guess=180, log_transform=True), N)\ntime_guess = np.linspace(0, 180, N)\n\n### Mass properties (a 152 near max gross, solo pilot)\nmass_props = asb.mass_properties_from_radius_of_gyration(\n    mass=1151.8 * u.lbm,\n    radius_of_gyration_x=2, radius_of_gyration_y=3, radius_of_gyration_z=3,  # m\n)\n\n### Initial state\ninit_state = {\n    \"x_e\": 0,\n    \"z_e\": -1000,  # 1000 m altitude (remember: Earth-axes z points down)\n    \"speed\": 107 * u.knot,  # cruise speed at the moment of engine failure\n    \"gamma\": 0,\n}\n\ndyn = asb.DynamicsPointMass2DSpeedGamma(\n    mass_props=mass_props,\n    x_e=opti.variable(init_guess=init_state[\"speed\"] * time_guess),\n    z_e=opti.variable(init_guess=np.linspace(init_state[\"z_e\"], 0, N)),\n    speed=opti.variable(init_guess=init_state[\"speed\"], n_vars=N),\n    gamma=opti.variable(init_guess=0, n_vars=N,\n                        lower_bound=-np.pi / 2, upper_bound=np.pi / 2),\n    alpha=opti.variable(init_guess=5, n_vars=N,  # the control input [deg]\n                        lower_bound=-5, upper_bound=15),\n)\nfor k in dyn.state.keys():\n    opti.subject_to(dyn.state[k][0] == init_state[k])\n\n### Forces: gravity, plus the full AeroBuildup model evaluated on the trajectory\ndyn.add_gravity_force(g=9.81)\n\naero = asb.AeroBuildup(airplane=airplane, op_point=dyn.op_point).run()\ndyn.add_force(*aero[\"F_w\"], axes=\"wind\")  # aero forces, in wind axes\n\n### Stay above ground, obey the equations of motion, and glide far\nopti.subject_to(dyn.altitude > 0)\ndyn.constrain_derivatives(opti, time)\nopti.minimize(-dyn.x_e[-1])\n\nt_start = perf_counter()\nsol = opti.solve(verbose=False)\ndyn = sol(dyn)\nt_solve = perf_counter() - t_start\n\nglide_range = dyn.x_e[-1]\nglide_time = sol(time)[-1]\nprint(f\"Solved in {sol.stats()['iter_count']} iterations ({t_solve:.0f} s).\")\nprint(f\"Maximum glide range: {glide_range / 1e3:.1f} km, reached in {glide_time / 60:.1f} min.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSolved in 26 iterations (73 s).\nMaximum glide range: 20.9 km, reached in 9.8 min.\n```\n:::\n:::\n\n\n::: {#cell-fig-12-glide-profile .cell execution_count=19}\n\n::: {.cell-output .cell-output-display}\n![The maximum-range glide, colored by true airspeed. The airplane first zoom-climbs — trading its excess cruise speed for altitude — then settles onto a steady best-glide descent, and finally flares in the last seconds to squeeze out the remaining kinetic energy. Note the extreme aspect-ratio distortion: the descent is actually a shallow ~3° slope.](12-dynamics-stack_files/figure-html/fig-12-glide-profile-output-1.png){#fig-12-glide-profile width=1025 height=571 fig-alt='Plot of altitude in meters versus downrange distance in kilometers. The path starts at 1000 meters, rises slightly to about 1100 meters over the first kilometer while the line color (indicating airspeed) lightens from dark blue (fast) to light blue (slow), then descends nearly linearly to zero altitude at about 21 kilometers downrange.'}\n:::\n:::\n\n\n::: {#cell-fig-12-glide-states .cell execution_count=20}\n\n::: {.cell-output .cell-output-display}\n![State and control histories for the optimal glide. Speed bleeds from 55 m/s cruise down to best-glide speed and holds (with a lightly-damped phugoid-like transient at the start); angle of attack sits on the best-L/D value for nearly the entire descent, then ramps to its limit in the final flare; the flight-path angle shows the initial zoom climb, the long shallow descent, and the flare.](12-dynamics-stack_files/figure-html/fig-12-glide-states-output-1.png){#fig-12-glide-states width=1039 height=1035 fig-alt='Three vertically stacked time-history plots over about 10 minutes: true airspeed dropping quickly from 55 to the mid-30s of meters per second with a brief oscillation, then decreasing very slowly before dropping at the end; angle of attack oscillating briefly then holding at about 3 degrees before ramping to 15 degrees in the final seconds; flight path angle spiking positive at the start, holding near -3 degrees, then rising toward zero at touchdown.'}\n:::\n:::\n\n\n### What the optimizer figured out\n\nThe solution reads like a flight-training syllabus:\n\n1. **Pitch up immediately.** Cruise speed (55 m/s) is far above best-glide speed; holding it would just burn energy into drag. The optimizer converts the excess kinetic energy into ~79 m of extra altitude — a zoom climb. This is precisely the \"pitch for best glide\" reflex that instructors drill.\n2. **Hold best glide.** For the long middle portion, the commanded angle of attack (median 3\\.0°) sits essentially on the best-$L/D$ value of 3\\.1° from our polar sweep — the dashed line in the middle panel above — at a steady 36 m/s. The slow decay in *true* airspeed during the descent isn't the pilot slowing down; it's the air getting denser on the way down at nearly-constant *indicated* airspeed.\n3. **Flare at the end.** In the last seconds, the optimizer pulls to the α limit, spending the remaining kinetic energy to stretch the glide a final few hundred meters. (A real pilot should keep an energy reserve for obstacles — the optimizer, told that the world ends at touchdown, does not.)\n\nAn energy audit confirms the physics. The airplane starts with an *energy height* (altitude plus kinetic energy expressed as height, $h + V^2/2g$) of 1154 m; multiplying by the best glide ratio of 18\\.7 bounds the achievable range at 21\\.6 km. The optimized trajectory achieves 20\\.9 km — 97% of that ideal, with the shortfall being drag paid during off-best-glide segments (the zoom climb and flare).\n\nFor a qualitative look at the whole trajectory, every `Dynamics` instance has a `draw()` method that renders the vehicle along its path in 3D (using PyVista), complete with an altitude drape and ground plane:\n\n::: {#cell-fig-12-glide-3d .cell execution_count=21}\n``` {.python .cell-code}\nimport pyvista as pv\n\npv.OFF_SCREEN = True  # render headless (no interactive window) for this book\n\nplotter = dyn.draw(\n    vehicle_model=airplane,\n    show=False,\n    n_vehicles_to_draw=7,\n    draw_global_grid=False,  # grid + axes get cluttered at this 20:1 aspect ratio\n    draw_global_axes=False,\n    draw_axes=False,\n)\nplotter.window_size = (1800, 420)\nplotter.camera.enable_parallel_projection()  # 2D-ify the view\nplotter.camera_position = \"xz\"\nplotter.camera.roll = 180  # NED axes: rotate so that \"up\" is up\nplotter.camera.azimuth = 180\nplotter.camera.zoom(3.6)\nplotter.screenshot(\"glide_3d.png\")\nplotter.close()\n\nfrom IPython.display import Image\n\nImage(\"glide_3d.png\")\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n![The glide trajectory rendered by `dyn.draw()`, viewed side-on: the airplane model is drawn at intervals along the path (auto-scaled for visibility), with a gray drape below it indicating height above the ground. The nose-high flare at far right is clearly visible.](12-dynamics-stack_files/figure-html/fig-12-glide-3d-output-1.png){#fig-12-glide-3d fig-alt='Side-view 3D rendering of the Cessna glide: seven airplane models spaced along a long, shallow descending flight path, each slightly nose-up, with a translucent gray surface connecting the path down to the ground.'}\n:::\n:::\n\n\nThe same modeling pattern — point-mass dynamics plus `AeroBuildup` forces — extends directly to 3D with `DynamicsPointMass3DSpeedGammaTrack`, which adds heading and bank: that's the setup for engine-out *turnback* studies (\"the impossible turn\"), terrain-following racing lines, and community-noise-optimal departure paths.\n\n## Dynamics without an optimizer {#sec-dynamics-stack-scipy}\n\n**The takeaway: the `Dynamics` classes are equation-of-motion calculators first and `Opti` citizens second — you can drive them with any ODE integrator, or with no integrator at all.**\n\nEverything above embedded the dynamics in an optimization problem. But sometimes you just want to *simulate*: no decisions, no objective, possibly stiff dynamics where an adaptive off-the-shelf integrator shines. Three methods make any `Dynamics` class a drop-in right-hand side for `scipy.integrate.solve_ivp`:\n\n* `dyn.state_derivatives()` — returns $d(\\text{state})/dt$ as a dict, given the instance's current state and accumulated forces;\n* `dyn.pack_state()` / `dyn.unpack_state()` — convert between that dict representation and the flat arrays `scipy` expects.\n\nHere's a worked example with genuinely nasty (near-singular) dynamics. It's your birthday; someone hands you a helium balloon — a 5-gram rubber sphere, 10 inches in diameter at sea level — and at the end of the day, you let it go. Where does it end up? Assume (unrealistically, as we'll see) that the balloon stretches freely so its internal pressure tracks ambient.\n\n::: {#a1590ecf .cell execution_count=22}\n``` {.python .cell-code}\nfrom scipy import integrate\nfrom aerosandbox.atmosphere.atmosphere import gas_constant_universal\n\n### Balloon parameters\nmass_rubber = 0.005  # kg\nhelium_molar_mass = 4.002602e-3  # kg/mol\natmo_sl = asb.Atmosphere(altitude=0)\nvolume_sl = 4 / 3 * np.pi * ((10 * u.inch) / 2) ** 3\nmass_helium = (  # PV = nRT\n    atmo_sl.pressure() * volume_sl * helium_molar_mass\n    / (gas_constant_universal * atmo_sl.temperature())\n)\n\ndyn_template = asb.DynamicsPointMass2DCartesian(\n    mass_props=asb.MassProperties(mass=mass_rubber + mass_helium)\n)\n\n\ndef balloon_volume(atmosphere):  # balloon stretches so P_inside tracks P_ambient\n    return (\n        mass_helium / helium_molar_mass * gas_constant_universal\n        * atmosphere.temperature() / atmosphere.pressure()\n    )\n\n\ndef equations_of_motion(t, y):\n    g = 9.81\n    dyn = dyn_template.get_new_instance_with_state(dyn_template.pack_state(y))\n    dyn.add_gravity_force(g=g)\n\n    # Buoyancy: weight of displaced air, pointing up (-z in Earth axes)\n    volume = balloon_volume(dyn.op_point.atmosphere)\n    dyn.add_force(Fz=-volume * dyn.op_point.atmosphere.density() * g, axes=\"earth\")\n\n    # Drag on a sphere (CD ~ 0.4 across the relevant Reynolds range)\n    radius = (volume * 3 / (4 * np.pi)) ** (1 / 3)\n    dyn.add_force(\n        Fx=-dyn.op_point.dynamic_pressure() * 0.4 * np.pi * radius**2, axes=\"wind\"\n    )\n\n    return dyn.unpack_state(dyn.state_derivatives())\n\n\nt_eval = np.cosspace(0, 6 * 3600, 300)  # six hours\nres = integrate.solve_ivp(\n    fun=equations_of_motion,\n    t_span=(t_eval.min(), t_eval.max()),\n    t_eval=t_eval,\n    y0=dyn_template.unpack_state({\"x_e\": 0, \"z_e\": 0, \"u_e\": 0, \"w_e\": 0}),\n    method=\"LSODA\",  # adaptive, handles the increasingly-stiff ascent\n)\n\n# Post-process by loading the result back into a (vectorized) Dynamics instance:\ndyn = dyn_template.get_new_instance_with_state(dyn_template.pack_state(res.y))\nballoon_radius = (balloon_volume(dyn.op_point.atmosphere) * 3 / (4 * np.pi)) ** (1 / 3)\nprint(f\"Altitude after 6 hours: {dyn.altitude[-1] / 1e3:.0f} km\")\nprint(f\"Balloon radius up there: {balloon_radius[-1]:.1f} m\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAltitude after 6 hours: 97 km\nBalloon radius up there: 14.6 m\n```\n:::\n:::\n\n\n::: {#cell-fig-12-balloon .cell execution_count=23}\n\n::: {.cell-output .cell-output-display}\n![The balloon ascends at an ever-increasing rate — because in this model it expands without limit as ambient pressure falls, so its buoyant volume grows while drag-per-volume shrinks. The lower panel shows the physically absurd consequence and the real answer: long before reaching these radii, the rubber pops.](12-dynamics-stack_files/figure-html/fig-12-balloon-output-1.png){#fig-12-balloon width=1035 height=810 fig-alt='Two stacked plots. Top: balloon altitude in kilometers versus time in hours, rising slowly at first then accelerating past 90 kilometers by six hours. Bottom: balloon radius in meters on a log scale versus altitude, growing from about 0.1 meters at sea level to several meters at high altitude.'}\n:::\n:::\n\n\nThe simulation says the balloon rises *forever, ever faster* — until you look at the radius plot and see why: our infinitely-stretchy balloon has swollen to 14\\.6 m across. In reality, of course, the rubber bursts within the first couple of kilometers of that curve. It's a good reminder that an integrator faithfully extrapolates your assumptions, not reality.\n\nOne last trick in the same spirit: because a `Dynamics` instance is just a container of state arrays with aerospace semantics, you can build one from *measured* data instead of simulation — for instance, loading GPS-logger data from a real flight into a `DynamicsPointMass3DSpeedGammaTrack` (positions, speed, and track from the log; flight-path and bank angles reconstructed from finite differences) and then calling `dyn.draw()` for an instant 3D replay of the flight. The dynamics stack doesn't care where the numbers came from.\n\n## Where to go next {#sec-dynamics-stack-next}\n\n* This chapter leaned on the trajectory-optimization machinery — collocation via `constrain_derivative()`, free final times, initial guesses as storyboards, and refinement studies — all of which is developed carefully in @sec-optimal-control.\n* The Cessna study treated `AeroBuildup` as a black box that happens to be differentiable. @sec-aircraft-aero-aerobuildup opens the box: what it models, when to trust it, and the higher-fidelity methods above it.\n* Dynamics closes the loop between *designing* an aircraft and *flying* it. The complete design studies — especially the transport-aircraft sizing of @sec-transport-problem — show mission analysis and vehicle design solved simultaneously in a single `Opti` problem, which is where this stack pays off most.\n\n",
    "supporting": [
      "12-dynamics-stack_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}