function [fitresult, gof] = createFit(log10_beta, log10_mass_lb)
%CREATEFIT(LOG10_BETA,LOG10_MASS_LB)
%  Create a fit.
%
%  Data for 'PowerFit' fit:
%      X Input : log10_beta
%      Y Output: log10_mass_lb
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Mar-2020 11:43:30


%% Fit: 'PowerFit'.
[xData, yData] = prepareCurveData( log10_beta, log10_mass_lb );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'PowerFit' );
h = plot( fitresult, xData, yData );
legend( h, 'log10_mass_lb vs. log10_beta', 'PowerFit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'log10_beta', 'Interpreter', 'none' );
ylabel( 'log10_mass_lb', 'Interpreter', 'none' );
grid on


